/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as R404RouteImport } from './routes/404';
import { Route as DownloadRouteImport } from './routes/download';
import { Route as ModulesRouteImport } from './routes/modules';
import { Route as PrivacyRouteImport } from './routes/privacy';
import { Route as SupportRouteImport } from './routes/support';
import { Route as BlogIndexRouteImport } from './routes/blog/index';
import { Route as BlogSlugRouteImport } from './routes/blog/$slug';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any);
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any);
const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any);
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any);
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any);
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any);
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/404': typeof R404Route;
  '/download': typeof DownloadRoute;
  '/modules': typeof ModulesRoute;
  '/privacy': typeof PrivacyRoute;
  '/support': typeof SupportRoute;
  '/blog/$slug': typeof BlogSlugRoute;
  '/blog/': typeof BlogIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/404': typeof R404Route;
  '/download': typeof DownloadRoute;
  '/modules': typeof ModulesRoute;
  '/privacy': typeof PrivacyRoute;
  '/support': typeof SupportRoute;
  '/blog/$slug': typeof BlogSlugRoute;
  '/blog': typeof BlogIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/404': typeof R404Route;
  '/download': typeof DownloadRoute;
  '/modules': typeof ModulesRoute;
  '/privacy': typeof PrivacyRoute;
  '/support': typeof SupportRoute;
  '/blog/$slug': typeof BlogSlugRoute;
  '/blog/': typeof BlogIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/404'
    | '/download'
    | '/modules'
    | '/privacy'
    | '/support'
    | '/blog/$slug'
    | '/blog/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/404'
    | '/download'
    | '/modules'
    | '/privacy'
    | '/support'
    | '/blog/$slug'
    | '/blog';
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/download'
    | '/modules'
    | '/privacy'
    | '/support'
    | '/blog/$slug'
    | '/blog/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  R404Route: typeof R404Route;
  DownloadRoute: typeof DownloadRoute;
  ModulesRoute: typeof ModulesRoute;
  PrivacyRoute: typeof PrivacyRoute;
  SupportRoute: typeof SupportRoute;
  BlogSlugRoute: typeof BlogSlugRoute;
  BlogIndexRoute: typeof BlogIndexRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/404': {
      id: '/404';
      path: '/404';
      fullPath: '/404';
      preLoaderRoute: typeof R404RouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/download': {
      id: '/download';
      path: '/download';
      fullPath: '/download';
      preLoaderRoute: typeof DownloadRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/modules': {
      id: '/modules';
      path: '/modules';
      fullPath: '/modules';
      preLoaderRoute: typeof ModulesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/privacy': {
      id: '/privacy';
      path: '/privacy';
      fullPath: '/privacy';
      preLoaderRoute: typeof PrivacyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/support': {
      id: '/support';
      path: '/support';
      fullPath: '/support';
      preLoaderRoute: typeof SupportRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/blog/': {
      id: '/blog/';
      path: '/blog';
      fullPath: '/blog/';
      preLoaderRoute: typeof BlogIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/blog/$slug': {
      id: '/blog/$slug';
      path: '/blog/$slug';
      fullPath: '/blog/$slug';
      preLoaderRoute: typeof BlogSlugRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  DownloadRoute: DownloadRoute,
  ModulesRoute: ModulesRoute,
  PrivacyRoute: PrivacyRoute,
  SupportRoute: SupportRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
