//! Portable backup: dump the *non-reproducible* identity + config state
//! (accounts, settings, acquisition indexers / download clients, watch history,
//! resume positions, invites, cron overrides) to a JSON document and restore it
//! on another server.
//!
//! The catalogue itself is **not** exported it's regenerated by a re-scan on
//! the target, which reproduces *identical* item IDs because the library
//! definitions (and their stable IDs) travel inside the `settings` rows. See
//! `crate::services::scan::ids` for the id derivation.
//!
//! Restore runs on a connection with `foreign_keys = OFF` so `progress` rows
//! insert even before the catalogue exists; rows whose item isn't present yet
//! sit inert and reconnect once the admin points the library at its media and
//! re-scans (same `lib_id` ⇒ same item id). Order-independent, no data loss.

use std::collections::BTreeMap;

use anyhow::{Context, Result};
use rusqlite::types::{Value as SqlValue, ValueRef};
use rusqlite::Connection;
use serde::{Deserialize, Serialize};
use serde_json::{Map, Value};

use super::{now_or_blank, Pool};

mod module_stores;
mod rows;

#[cfg(test)]
mod test_support;

use module_stores::{dump_store, module_stores, restore_modules};
use rows::{dump_query, restore_rows};

// On-disk shape version; bump on an incompatible change.
const VERSION: u32 = 1;

// Tables carried by a portable backup. Everything else (catalogue, embeddings,
// AI sections, sessions, job run history, and the machine-specific `downloads`
// torrent state) is regenerated and left out. `settings` carries the VPN /
// naming / acquisition preferences; `requests` + `wanted` carry the users' media
// wishlist and its episode ledger. `progress`/`watched`/`my_list` are item-keyed
// user state that re-links by `item_id` once a re-scan recreates the catalogue
// with matching ids.
//
// A module's own tables are NOT named here any more -- they are not in this
// database. Each installed module's private store is walked whole (see
// [`module_stores`]), which is both how the admin's indexer keys and download
// client passwords still travel and how this list stopped needing to know which
// modules exist.
const TABLES: &[&str] = &[
    "users",
    "settings",
    "requests",
    "wanted",
    "invites",
    "play_history",
    "job_schedules",
    "progress",
    "watched",
    "my_list",
];

/// A portable backup: one row-set per exported table, plus metadata. Serde-only
/// (the clients treat the file as an opaque blob), so no ts-rs wire type.
#[derive(Debug, Serialize, Deserialize)]
pub struct BackupDoc {
    pub version: u32,
    pub exported_at: String,
    // table name → rows, each row a `{column: value}` object.
    pub tables: BTreeMap<String, Vec<Map<String, Value>>>,
    // User-uploaded files the rows reference but that live outside the DB
    // (custom avatars in the image cache): cache filename → hex of the bytes.
    // Populated by `services::backup`, not the DB layer. `default` so older
    // (pre-assets) backups still deserialize.
    #[serde(default)]
    pub assets: BTreeMap<String, String>,
    // Each installed module's own database: module id → table → rows. `default`
    // so a backup taken before modules had their own file still deserializes.
    #[serde(default)]
    pub modules: BTreeMap<String, BTreeMap<String, Vec<Map<String, Value>>>>,
}

/// Dump every portable table, plus every installed module's own database, to a
/// [`BackupDoc`]. A table that is absent is skipped rather than erroring, which
/// is the normal state of a database whose optional features were never used.
pub fn export_portable(pool: &Pool, data_dir: &std::path::Path) -> Result<BackupDoc> {
    let conn = pool.get()?;
    let mut tables = BTreeMap::new();
    for &t in TABLES {
        if !table_exists(&conn, t)? {
            continue;
        }
        tables.insert(t.to_string(), dump_query(&conn, &format!("SELECT * FROM {t}"))?);
    }
    let mut modules = BTreeMap::new();
    for (id, path) in module_stores(data_dir) {
        // One unreadable module store must not cost the operator the rest of the
        // backup; it is reported and the export goes on.
        match dump_store(&path) {
            Ok(store) if !store.is_empty() => {
                modules.insert(id, store);
            }
            Ok(_) => {}
            Err(error) => {
                tracing::warn!(module = %id, %error, "module database not backed up")
            }
        }
    }
    Ok(BackupDoc {
        version: VERSION,
        exported_at: now_or_blank(),
        tables,
        assets: BTreeMap::new(),
        modules,
    })
}

// Whether `name` is a table in the current database (module-owned tables may not
// be, see [`export_portable`]).
fn table_exists(conn: &Connection, name: &str) -> Result<bool> {
    let n: i64 = conn.query_row(
        "SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name=?1",
        [name],
        |r| r.get(0),
    )?;
    Ok(n > 0)
}

/// Restore a [`BackupDoc`] into the database, replacing rows by primary key.
/// Runs in one transaction with foreign keys disabled (see module docs). When
/// `reset` is set, the portable tables are emptied first (a true A→B clone)
/// still inside the same transaction, so a crash mid-restore rolls back wholesale.
/// Returns `(table, rows_written)` pairs in restore order.
pub fn import_portable(
    pool: &Pool,
    data_dir: &std::path::Path,
    doc: &BackupDoc,
    reset: bool,
) -> Result<Vec<(String, usize)>> {
    if doc.version > VERSION {
        anyhow::bail!("backup version {} is newer than supported {VERSION}", doc.version);
    }
    let mut conn = pool.get()?;
    // Insert across the catalogue gap: `progress.item_id` references rows that a
    // fresh target doesn't have yet. Orphans are inert and reconnect on re-scan.
    // The pragma must toggle *outside* a transaction; restore it before the
    // connection returns to the pool (pooled conns reapply PRAGMAS only on open).
    conn.execute_batch("PRAGMA foreign_keys = OFF;")?;
    let result = restore_all(&mut conn, doc, reset);
    let _ = conn.execute_batch("PRAGMA foreign_keys = ON;");
    let mut summary = result?;
    summary.extend(restore_modules(data_dir, doc, reset));
    Ok(summary)
}

// The transactional body of [`import_portable`], split out so the caller can
// restore `foreign_keys` whether it succeeds or fails.
fn restore_all(conn: &mut rusqlite::Connection, doc: &BackupDoc, reset: bool) -> Result<Vec<(String, usize)>> {
    let tx = conn.transaction()?;
    if reset {
        for &t in TABLES {
            if table_exists(&tx, t)? {
                tx.execute(&format!("DELETE FROM {t}"), [])?;
            }
        }
    }
    let mut summary = Vec::new();
    for &t in TABLES {
        if let Some(rows) = doc.tables.get(t) {
            // Skip a table the target lacks (a module present in the source but
            // absent here); its config simply isn't restored.
            if !table_exists(&tx, t)? {
                continue;
            }
            let n = restore_rows(&tx, t, rows).with_context(|| format!("restoring {t}"))?;
            summary.push((t.to_string(), n));
        }
    }
    tx.commit()?;
    Ok(summary)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::backup::test_support::*;

    #[test]
    fn roundtrip_restores_state_and_keeps_orphan_progress() {
        let src = fresh_pool("src");
        {
            let c = src.get().unwrap();
            c.execute("INSERT INTO libraries (id,name,kind,path,added_at) VALUES ('lib','L','movie','/x','t')", []).unwrap();
            c.execute("INSERT INTO items (id,kind,title,container,library,added_at) VALUES ('it1','movie','Film','mkv','lib','t')", []).unwrap();
            c.execute("INSERT INTO users (id,email,username,password_hash,created_at) VALUES ('u1','a@b.c','Al','ph','t')", []).unwrap();
            c.execute("INSERT INTO settings (key,value,updated_at) VALUES ('serverName','\"My KROMA\"','t')", []).unwrap();
            c.execute("INSERT INTO progress (user_id,item_id,position_ms,duration_ms,updated_at) VALUES ('u1','it1',1000,5000,'t')", []).unwrap();
            c.execute("INSERT INTO play_history (id,kind,title,started_at,ended_at) VALUES ('h1','movie','Film',1,2)", []).unwrap();
            c.execute("INSERT INTO watched (user_id,item_id,watched_at) VALUES ('u1','it1','t')", []).unwrap();
            c.execute("INSERT INTO my_list (user_id,item_id,added_at) VALUES ('u1','it1','t')", []).unwrap();
            // A user's media request (wishlist) + its episode ledger.
            c.execute("INSERT INTO requests (id,kind,tmdb_id,title,status,created_at,updated_at) VALUES ('rq1','movie',603,'The Matrix','approved',1,1)", []).unwrap();
            c.execute("INSERT INTO wanted (id,request_id,kind,tmdb_id,title,status,updated_at) VALUES ('wt1','rq1','movie',603,'The Matrix','wanted',1)", []).unwrap();
        }

        let doc = export_portable(&src, &data_dir(&src)).unwrap();
        assert_eq!(doc.tables["users"].len(), 1);
        assert_eq!(doc.tables["progress"].len(), 1);
        assert_eq!(doc.tables["watched"].len(), 1);
        assert_eq!(doc.tables["my_list"].len(), 1);
        assert_eq!(doc.tables["requests"].len(), 1);
        assert_eq!(doc.tables["wanted"].len(), 1);
        // The catalogue is NOT exported only the portable identity tables.
        assert!(!doc.tables.contains_key("items"));

        // Fresh target with no catalogue (items table empty).
        let dst = fresh_pool("dst");
        import_portable(&dst, &data_dir(&dst), &doc, false).unwrap();

        assert_eq!(count(&dst, "users"), 1);
        assert_eq!(count(&dst, "play_history"), 1);
        // The orphan progress row survives the missing item (FK off on import) and
        // will reconnect once a re-scan recreates `it1` with the same id.
        assert_eq!(count(&dst, "items"), 0);
        assert_eq!(count(&dst, "progress"), 1);
        assert_eq!(count(&dst, "watched"), 1);
        assert_eq!(count(&dst, "my_list"), 1);
        assert_eq!(count(&dst, "requests"), 1);
        assert_eq!(count(&dst, "wanted"), 1);

        let server_name: String = dst
            .get()
            .unwrap()
            .query_row("SELECT value FROM settings WHERE key='serverName'", [], |r| r.get(0))
            .unwrap();
        assert_eq!(server_name, "\"My KROMA\"");

        // foreign_keys must be back ON for the next user of any pooled connection.
        let fk: i64 = dst.get().unwrap().query_row("PRAGMA foreign_keys", [], |r| r.get(0)).unwrap();
        assert_eq!(fk, 1);
    }

    #[test]
    fn a_backup_from_a_newer_server_is_refused_rather_than_half_restored() {
        let dst = fresh_pool("newer");
        let doc = BackupDoc { version: VERSION + 1, ..empty_doc() };
        let err = import_portable(&dst, &data_dir(&dst), &doc, false).unwrap_err().to_string();
        assert!(err.contains("newer than supported"), "{err}");
    }

    #[test]
    fn a_table_the_target_does_not_have_is_skipped_rather_than_failing_the_restore() {
        let dst = crate::testing::temp_pool("bkp-no-module");
        let mut doc = empty_doc();
        doc.tables.insert(
            "indexers".into(),
            vec![Map::from_iter([("id".to_string(), Value::from("ix1"))])],
        );
        doc.tables.insert(
            "users".into(),
            vec![Map::from_iter([
                ("id".to_string(), Value::from("u1")),
                ("email".to_string(), Value::from("a@b.c")),
                ("username".to_string(), Value::from("Al")),
                ("password_hash".to_string(), Value::from("ph")),
                ("created_at".to_string(), Value::from("t")),
            ])],
        );

        let summary = import_portable(&dst, &data_dir(&dst), &doc, true).unwrap();
        assert_eq!(summary, vec![("users".to_string(), 1)]);
        assert_eq!(count(&dst, "users"), 1);
    }
}
