//! Portable backup: dump the *non-reproducible* identity + config state
//! (accounts, settings, acquisition indexers / download clients, watch history,
//! resume positions, invites, cron overrides) to a JSON document and restore it
//! on another server.
//!
//! The catalogue itself is **not** exported it's regenerated by a re-scan on
//! the target, which reproduces *identical* item IDs because the library
//! definitions (and their stable IDs) travel inside the `settings` rows. See
//! `crate::services::scan::ids` for the id derivation.
//!
//! Restore runs on a connection with `foreign_keys = OFF` so `progress` rows
//! insert even before the catalogue exists; rows whose item isn't present yet
//! sit inert and reconnect once the admin points the library at its media and
//! re-scans (same `lib_id` ⇒ same item id). Order-independent, no data loss.

use std::collections::BTreeMap;

use anyhow::{Context, Result};
use rusqlite::types::{Value as SqlValue, ValueRef};
use rusqlite::Connection;
use serde::{Deserialize, Serialize};
use serde_json::{Map, Value};

use super::{now_or_blank, Pool};

// On-disk shape version; bump on an incompatible change.
const VERSION: u32 = 1;

// Tables carried by a portable backup. Everything else (catalogue, embeddings,
// AI sections, sessions, job run history, and the machine-specific `downloads`
// torrent state) is regenerated and left out. `settings` carries the VPN /
// naming / acquisition preferences; `requests` + `wanted` carry the users' media
// wishlist and its episode ledger. `progress`/`watched`/`my_list` are item-keyed
// user state that re-links by `item_id` once a re-scan recreates the catalogue
// with matching ids.
//
// A module's own tables are NOT named here any more -- they are not in this
// database. Each installed module's private store is walked whole (see
// [`module_stores`]), which is both how the admin's indexer keys and download
// client passwords still travel and how this list stopped needing to know which
// modules exist.
const TABLES: &[&str] = &[
    "users",
    "settings",
    "requests",
    "wanted",
    "invites",
    "play_history",
    "job_schedules",
    "progress",
    "watched",
    "my_list",
];

/// A portable backup: one row-set per exported table, plus metadata. Serde-only
/// (the clients treat the file as an opaque blob), so no ts-rs wire type.
#[derive(Debug, Serialize, Deserialize)]
pub struct BackupDoc {
    pub version: u32,
    pub exported_at: String,
    // table name → rows, each row a `{column: value}` object.
    pub tables: BTreeMap<String, Vec<Map<String, Value>>>,
    // User-uploaded files the rows reference but that live outside the DB
    // (custom avatars in the image cache): cache filename → hex of the bytes.
    // Populated by `services::backup`, not the DB layer. `default` so older
    // (pre-assets) backups still deserialize.
    #[serde(default)]
    pub assets: BTreeMap<String, String>,
    // Each installed module's own database: module id → table → rows. `default`
    // so a backup taken before modules had their own file still deserializes.
    #[serde(default)]
    pub modules: BTreeMap<String, BTreeMap<String, Vec<Map<String, Value>>>>,
}

/// Dump every portable table, plus every installed module's own database, to a
/// [`BackupDoc`]. A table that is absent is skipped rather than erroring, which
/// is the normal state of a database whose optional features were never used.
pub fn export_portable(pool: &Pool, data_dir: &std::path::Path) -> Result<BackupDoc> {
    let conn = pool.get()?;
    let mut tables = BTreeMap::new();
    for &t in TABLES {
        if !table_exists(&conn, t)? {
            continue;
        }
        tables.insert(t.to_string(), dump_query(&conn, &format!("SELECT * FROM {t}"))?);
    }
    let mut modules = BTreeMap::new();
    for (id, path) in module_stores(data_dir) {
        // One unreadable module store must not cost the operator the rest of the
        // backup; it is reported and the export goes on.
        match dump_store(&path) {
            Ok(store) if !store.is_empty() => {
                modules.insert(id, store);
            }
            Ok(_) => {}
            Err(error) => {
                tracing::warn!(module = %id, %error, "module database not backed up")
            }
        }
    }
    Ok(BackupDoc {
        version: VERSION,
        exported_at: now_or_blank(),
        tables,
        assets: BTreeMap::new(),
        modules,
    })
}

/// Every installed module's own database, as `(module id, path)`. Empty when
/// nothing is installed, which is the zero-module base build.
fn module_stores(data_dir: &std::path::Path) -> Vec<(String, std::path::PathBuf)> {
    let Ok(entries) = std::fs::read_dir(data_dir.join("modules")) else {
        return Vec::new();
    };
    let mut out: Vec<(String, std::path::PathBuf)> = entries
        .filter_map(|e| e.ok())
        .filter_map(|e| {
            let store = e.path().join("module.sqlite");
            let id = e.file_name().to_string_lossy().into_owned();
            store.is_file().then_some((id, store))
        })
        .collect();
    out.sort();
    out
}

// Every user table in one module's database, whatever they are: the core does
// not know a module's schema and has no business learning it.
fn dump_store(path: &std::path::Path) -> Result<BTreeMap<String, Vec<Map<String, Value>>>> {
    let conn = Connection::open(path)?;
    let names: Vec<String> = conn
        .prepare("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name")?
        .query_map([], |r| r.get(0))?
        .collect::<std::result::Result<_, _>>()?;
    let mut out = BTreeMap::new();
    for name in names {
        out.insert(name.clone(), dump_query(&conn, &format!("SELECT * FROM \"{name}\""))?);
    }
    Ok(out)
}

// Whether `name` is a table in the current database (module-owned tables may not
// be, see [`export_portable`]).
fn table_exists(conn: &Connection, name: &str) -> Result<bool> {
    let n: i64 = conn.query_row(
        "SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name=?1",
        [name],
        |r| r.get(0),
    )?;
    Ok(n > 0)
}

/// Restore a [`BackupDoc`] into the database, replacing rows by primary key.
/// Runs in one transaction with foreign keys disabled (see module docs). When
/// `reset` is set, the portable tables are emptied first (a true A→B clone)
/// still inside the same transaction, so a crash mid-restore rolls back wholesale.
/// Returns `(table, rows_written)` pairs in restore order.
pub fn import_portable(
    pool: &Pool,
    data_dir: &std::path::Path,
    doc: &BackupDoc,
    reset: bool,
) -> Result<Vec<(String, usize)>> {
    if doc.version > VERSION {
        anyhow::bail!("backup version {} is newer than supported {VERSION}", doc.version);
    }
    let mut conn = pool.get()?;
    // Insert across the catalogue gap: `progress.item_id` references rows that a
    // fresh target doesn't have yet. Orphans are inert and reconnect on re-scan.
    // The pragma must toggle *outside* a transaction; restore it before the
    // connection returns to the pool (pooled conns reapply PRAGMAS only on open).
    conn.execute_batch("PRAGMA foreign_keys = OFF;")?;
    let result = restore_all(&mut conn, doc, reset);
    let _ = conn.execute_batch("PRAGMA foreign_keys = ON;");
    let mut summary = result?;
    summary.extend(restore_modules(data_dir, doc, reset));
    Ok(summary)
}

// A module's rows go back into that module's own database, and only into tables
// it has already created. A module absent from this server (or one that has
// never started, so its schema does not exist yet) is skipped: its rows stay in
// the document and land the next time the same backup is restored somewhere the
// module IS installed.
fn restore_modules(
    data_dir: &std::path::Path,
    doc: &BackupDoc,
    reset: bool,
) -> Vec<(String, usize)> {
    let mut summary = Vec::new();
    for (id, tables) in &doc.modules {
        let path = data_dir.join("modules").join(id).join("module.sqlite");
        if !path.is_file() {
            tracing::info!(module = %id, "not installed here; its rows are not restored");
            continue;
        }
        match restore_store(&path, tables, reset) {
            Ok(counts) => summary.extend(counts.into_iter().map(|(t, n)| (format!("{id}/{t}"), n))),
            Err(error) => tracing::warn!(module = %id, %error, "module rows not restored"),
        }
    }
    summary
}

fn restore_store(
    path: &std::path::Path,
    tables: &BTreeMap<String, Vec<Map<String, Value>>>,
    reset: bool,
) -> Result<Vec<(String, usize)>> {
    let mut conn = Connection::open(path)?;
    let tx = conn.transaction()?;
    let mut summary = Vec::new();
    for (name, rows) in tables {
        if !is_ident(name) || !table_exists(&tx, name)? {
            continue;
        }
        if reset {
            tx.execute(&format!("DELETE FROM \"{name}\""), [])?;
        }
        let n = restore_rows(&tx, name, rows).with_context(|| format!("restoring {name}"))?;
        summary.push((name.clone(), n));
    }
    tx.commit()?;
    Ok(summary)
}

// The transactional body of [`import_portable`], split out so the caller can
// restore `foreign_keys` whether it succeeds or fails.
fn restore_all(conn: &mut rusqlite::Connection, doc: &BackupDoc, reset: bool) -> Result<Vec<(String, usize)>> {
    let tx = conn.transaction()?;
    if reset {
        for &t in TABLES {
            if table_exists(&tx, t)? {
                tx.execute(&format!("DELETE FROM {t}"), [])?;
            }
        }
    }
    let mut summary = Vec::new();
    for &t in TABLES {
        if let Some(rows) = doc.tables.get(t) {
            // Skip a table the target lacks (a module present in the source but
            // absent here); its config simply isn't restored.
            if !table_exists(&tx, t)? {
                continue;
            }
            let n = restore_rows(&tx, t, rows).with_context(|| format!("restoring {t}"))?;
            summary.push((t.to_string(), n));
        }
    }
    tx.commit()?;
    Ok(summary)
}

// Run `sql` and map every row to a `{column: value}` JSON object.
fn dump_query(conn: &Connection, sql: &str) -> Result<Vec<Map<String, Value>>> {
    let mut stmt = conn.prepare(sql)?;
    let cols: Vec<String> = stmt.column_names().into_iter().map(String::from).collect();
    let mut rows = stmt.query([])?;
    let mut out = Vec::new();
    while let Some(row) = rows.next()? {
        let mut obj = Map::new();
        for (i, col) in cols.iter().enumerate() {
            obj.insert(col.clone(), sql_to_json(row.get_ref(i)?));
        }
        out.push(obj);
    }
    Ok(out)
}

// `INSERT OR REPLACE` each row into `table` (replace-by-primary-key). Column
// names are validated as plain identifiers before interpolation.
fn restore_rows(conn: &Connection, table: &str, rows: &[Map<String, Value>]) -> Result<usize> {
    let mut written = 0;
    for row in rows {
        let cols: Vec<&String> = row.keys().filter(|c| is_ident(c)).collect();
        if cols.is_empty() {
            continue;
        }
        let col_list = cols.iter().map(|c| format!("\"{c}\"")).collect::<Vec<_>>().join(",");
        let placeholders = (1..=cols.len()).map(|i| format!("?{i}")).collect::<Vec<_>>().join(",");
        let sql = format!("INSERT OR REPLACE INTO \"{table}\" ({col_list}) VALUES ({placeholders})");
        let values: Vec<SqlValue> = cols.iter().map(|c| json_to_sql(&row[*c])).collect();
        conn.execute(&sql, rusqlite::params_from_iter(values.iter()))?;
        written += 1;
    }
    Ok(written)
}

// SQLite value → JSON. Blobs become a byte array (none of the exported tables
// have blob columns today, but keep it lossless).
fn sql_to_json(v: ValueRef<'_>) -> Value {
    match v {
        ValueRef::Null => Value::Null,
        ValueRef::Integer(i) => Value::from(i),
        ValueRef::Real(f) => Value::from(f),
        ValueRef::Text(t) => Value::from(String::from_utf8_lossy(t).into_owned()),
        ValueRef::Blob(b) => Value::from(b.to_vec()),
    }
}

// JSON → SQLite value, inverse of [`sql_to_json`]. Stored-JSON text columns
// (`settings.value`, `permissions`, …) round-trip as `Text`.
fn json_to_sql(v: &Value) -> SqlValue {
    match v {
        Value::Null => SqlValue::Null,
        Value::Bool(b) => SqlValue::Integer(*b as i64),
        Value::Number(n) => n
            .as_i64()
            .map(SqlValue::Integer)
            .unwrap_or_else(|| SqlValue::Real(n.as_f64().unwrap_or(0.0))),
        Value::String(s) => SqlValue::Text(s.clone()),
        Value::Array(a) => SqlValue::Blob(a.iter().filter_map(|x| x.as_u64().map(|n| n as u8)).collect()),
        Value::Object(_) => SqlValue::Text(v.to_string()),
    }
}

// A safe SQL identifier (`[A-Za-z0-9_]+`) guards interpolated column names.
fn is_ident(s: &str) -> bool {
    !s.is_empty() && s.bytes().all(|b| b.is_ascii_alphanumeric() || b == b'_')
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::testing::TempPool;

    fn fresh_pool(tag: &str) -> TempPool {
        crate::testing::temp_pool(&format!("bkp-{tag}"))
    }

    // The data directory the pool's database sits in, which is also where a
    // module's own store lives.
    fn data_dir(pool: &Pool) -> std::path::PathBuf {
        pool.path().parent().expect("the database has a directory").to_path_buf()
    }

    // Stand up one module's own database the way a running module would: the
    // indexer's table, holding an API key nobody wants to lose in a restore.
    fn seed_indexer_store(dir: &std::path::Path, rows: &str) -> std::path::PathBuf {
        let store = dir.join("modules").join("tv.kroma.indexer").join("module.sqlite");
        std::fs::create_dir_all(store.parent().unwrap()).unwrap();
        let conn = Connection::open(&store).unwrap();
        conn.execute_batch(&format!(
            "CREATE TABLE IF NOT EXISTS indexers (id TEXT PRIMARY KEY, name TEXT NOT NULL, \
             api_key TEXT NOT NULL DEFAULT '', created_at INTEGER NOT NULL);{rows}"
        ))
        .unwrap();
        store
    }

    fn store_count(store: &std::path::Path, table: &str) -> i64 {
        Connection::open(store)
            .unwrap()
            .query_row(&format!("SELECT count(*) FROM {table}"), [], |r| r.get(0))
            .unwrap()
    }

    fn count(pool: &Pool, table: &str) -> i64 {
        pool.get()
            .unwrap()
            .query_row(&format!("SELECT COUNT(*) FROM {table}"), [], |r| r.get(0))
            .unwrap()
    }

    #[test]
    fn roundtrip_restores_state_and_keeps_orphan_progress() {
        let src = fresh_pool("src");
        {
            let c = src.get().unwrap();
            c.execute("INSERT INTO libraries (id,name,kind,path,added_at) VALUES ('lib','L','movie','/x','t')", []).unwrap();
            c.execute("INSERT INTO items (id,kind,title,container,library,added_at) VALUES ('it1','movie','Film','mkv','lib','t')", []).unwrap();
            c.execute("INSERT INTO users (id,email,username,password_hash,created_at) VALUES ('u1','a@b.c','Al','ph','t')", []).unwrap();
            c.execute("INSERT INTO settings (key,value,updated_at) VALUES ('serverName','\"My KROMA\"','t')", []).unwrap();
            c.execute("INSERT INTO progress (user_id,item_id,position_ms,duration_ms,updated_at) VALUES ('u1','it1',1000,5000,'t')", []).unwrap();
            c.execute("INSERT INTO play_history (id,kind,title,started_at,ended_at) VALUES ('h1','movie','Film',1,2)", []).unwrap();
            c.execute("INSERT INTO watched (user_id,item_id,watched_at) VALUES ('u1','it1','t')", []).unwrap();
            c.execute("INSERT INTO my_list (user_id,item_id,added_at) VALUES ('u1','it1','t')", []).unwrap();
            // A user's media request (wishlist) + its episode ledger.
            c.execute("INSERT INTO requests (id,kind,tmdb_id,title,status,created_at,updated_at) VALUES ('rq1','movie',603,'The Matrix','approved',1,1)", []).unwrap();
            c.execute("INSERT INTO wanted (id,request_id,kind,tmdb_id,title,status,updated_at) VALUES ('wt1','rq1','movie',603,'The Matrix','wanted',1)", []).unwrap();
        }

        let doc = export_portable(&src, &data_dir(&src)).unwrap();
        assert_eq!(doc.tables["users"].len(), 1);
        assert_eq!(doc.tables["progress"].len(), 1);
        assert_eq!(doc.tables["watched"].len(), 1);
        assert_eq!(doc.tables["my_list"].len(), 1);
        assert_eq!(doc.tables["requests"].len(), 1);
        assert_eq!(doc.tables["wanted"].len(), 1);
        // The catalogue is NOT exported only the portable identity tables.
        assert!(!doc.tables.contains_key("items"));

        // Fresh target with no catalogue (items table empty).
        let dst = fresh_pool("dst");
        import_portable(&dst, &data_dir(&dst), &doc, false).unwrap();

        assert_eq!(count(&dst, "users"), 1);
        assert_eq!(count(&dst, "play_history"), 1);
        // The orphan progress row survives the missing item (FK off on import) and
        // will reconnect once a re-scan recreates `it1` with the same id.
        assert_eq!(count(&dst, "items"), 0);
        assert_eq!(count(&dst, "progress"), 1);
        assert_eq!(count(&dst, "watched"), 1);
        assert_eq!(count(&dst, "my_list"), 1);
        assert_eq!(count(&dst, "requests"), 1);
        assert_eq!(count(&dst, "wanted"), 1);

        let server_name: String = dst
            .get()
            .unwrap()
            .query_row("SELECT value FROM settings WHERE key='serverName'", [], |r| r.get(0))
            .unwrap();
        assert_eq!(server_name, "\"My KROMA\"");

        // foreign_keys must be back ON for the next user of any pooled connection.
        let fk: i64 = dst.get().unwrap().query_row("PRAGMA foreign_keys", [], |r| r.get(0)).unwrap();
        assert_eq!(fk, 1);
    }

    fn empty_doc() -> BackupDoc {
        BackupDoc {
            version: VERSION,
            exported_at: "t".into(),
            tables: BTreeMap::new(),
            assets: BTreeMap::new(),
            modules: BTreeMap::new(),
        }
    }

    #[test]
    fn a_modules_own_database_travels_with_the_backup() {
        // The indexer API keys and download-client passwords moved out of the
        // core database, and losing them in a restore would be the whole point
        // of a backup gone.
        let src = fresh_pool("mod-src");
        let src_dir = data_dir(&src);
        seed_indexer_store(
            &src_dir,
            "INSERT INTO indexers VALUES ('ix1','Jackett','secret',1);",
        );

        let doc = export_portable(&src, &src_dir).unwrap();
        let dumped = &doc.modules["tv.kroma.indexer"]["indexers"];
        assert_eq!(dumped.len(), 1);
        assert_eq!(dumped[0]["api_key"], Value::from("secret"));

        // The target has the module installed and started, so its schema exists.
        let dst = fresh_pool("mod-dst");
        let dst_dir = data_dir(&dst);
        let dst_store = seed_indexer_store(&dst_dir, "");

        let summary = import_portable(&dst, &dst_dir, &doc, false).unwrap();
        assert!(summary.contains(&("tv.kroma.indexer/indexers".to_string(), 1)), "{summary:?}");
        assert_eq!(store_count(&dst_store, "indexers"), 1);
        let key: String = Connection::open(&dst_store)
            .unwrap()
            .query_row("SELECT api_key FROM indexers WHERE id='ix1'", [], |r| r.get(0))
            .unwrap();
        assert_eq!(key, "secret");
    }

    #[test]
    fn rows_for_a_module_this_server_does_not_have_are_left_in_the_document() {
        // Restoring onto a server where the module is not installed must not
        // fail the restore, and must not invent a database for it either.
        let dst = fresh_pool("mod-absent");
        let dir = data_dir(&dst);
        let mut doc = empty_doc();
        doc.modules.insert(
            "tv.kroma.indexer".into(),
            BTreeMap::from([(
                "indexers".to_string(),
                vec![Map::from_iter([("id".to_string(), Value::from("ix1"))])],
            )]),
        );

        assert!(import_portable(&dst, &dir, &doc, false).unwrap().is_empty());
        assert!(!dir.join("modules/tv.kroma.indexer/module.sqlite").exists());
    }

    #[test]
    fn a_backup_from_a_newer_server_is_refused_rather_than_half_restored() {
        let dst = fresh_pool("newer");
        let doc = BackupDoc { version: VERSION + 1, ..empty_doc() };
        let err = import_portable(&dst, &data_dir(&dst), &doc, false).unwrap_err().to_string();
        assert!(err.contains("newer than supported"), "{err}");
    }

    #[test]
    fn a_table_the_target_does_not_have_is_skipped_rather_than_failing_the_restore() {
        let dst = crate::testing::temp_pool("bkp-no-module");
        let mut doc = empty_doc();
        doc.tables.insert(
            "indexers".into(),
            vec![Map::from_iter([("id".to_string(), Value::from("ix1"))])],
        );
        doc.tables.insert(
            "users".into(),
            vec![Map::from_iter([
                ("id".to_string(), Value::from("u1")),
                ("email".to_string(), Value::from("a@b.c")),
                ("username".to_string(), Value::from("Al")),
                ("password_hash".to_string(), Value::from("ph")),
                ("created_at".to_string(), Value::from("t")),
            ])],
        );

        let summary = import_portable(&dst, &data_dir(&dst), &doc, true).unwrap();
        assert_eq!(summary, vec![("users".to_string(), 1)]);
        assert_eq!(count(&dst, "users"), 1);
    }

    #[test]
    fn a_row_whose_columns_are_all_unsafe_identifiers_is_skipped() {
        let dst = fresh_pool("idents");
        let mut doc = empty_doc();
        doc.tables.insert(
            "users".into(),
            vec![Map::from_iter([("id); DROP TABLE users --".to_string(), Value::from("u1"))])],
        );
        assert_eq!(import_portable(&dst, &data_dir(&dst), &doc, false).unwrap(), vec![("users".to_string(), 0)]);
        assert_eq!(count(&dst, "users"), 0);
    }

    #[test]
    fn every_json_value_kind_maps_onto_a_sqlite_value() {
        assert_eq!(json_to_sql(&Value::Null), SqlValue::Null);
        assert_eq!(json_to_sql(&Value::Bool(true)), SqlValue::Integer(1));
        assert_eq!(json_to_sql(&Value::Bool(false)), SqlValue::Integer(0));
        assert_eq!(json_to_sql(&serde_json::json!(42)), SqlValue::Integer(42));
        assert_eq!(json_to_sql(&serde_json::json!(1.5)), SqlValue::Real(1.5));
        assert_eq!(json_to_sql(&serde_json::json!("hi")), SqlValue::Text("hi".into()));
        assert_eq!(json_to_sql(&serde_json::json!([1, 2, 255])), SqlValue::Blob(vec![1, 2, 255]));
        assert_eq!(
            json_to_sql(&serde_json::json!({ "a": 1 })),
            SqlValue::Text(r#"{"a":1}"#.into())
        );
    }

    #[test]
    fn every_sqlite_value_kind_survives_the_dump_as_json() {
        let pool = crate::testing::temp_pool("bkp-values");
        let conn = pool.get().unwrap();
        conn.execute_batch(
            "CREATE TABLE v (i INTEGER, r REAL, t TEXT, b BLOB, n TEXT);\
             INSERT INTO v VALUES (7, 1.5, 'text', x'00ff', NULL);",
        )
        .unwrap();

        let rows = dump_query(&conn, "SELECT * FROM v").unwrap();
        assert_eq!(rows[0]["i"], Value::from(7));
        assert_eq!(rows[0]["r"], Value::from(1.5));
        assert_eq!(rows[0]["t"], Value::from("text"));
        assert_eq!(rows[0]["b"], serde_json::json!([0, 255]));
        assert_eq!(rows[0]["n"], Value::Null);
    }
}
