//! Catalog writes: metadata attachment, ffprobe results and the scan diff-sync.

use std::collections::HashMap;

use super::*;

use kroma_domain::{CastMember, Library, LibraryKind, Metadata, Show};

pub fn set_item_metadata(pool: &Pool, id: &str, meta: &Metadata) -> Result<()> {
    let conn = pool.get()?;
    let json = serde_json::to_string(meta)?;
    conn.execute("UPDATE items SET metadata = ?2 WHERE id = ?1", params![id, json])?;
    Ok(())
}

/// Dual-writes one subject's metadata: a language-agnostic [`metadata_core`]
/// row plus a [`translations`] row per language. Character names align by
/// index to `core_meta`'s cast (TMDB keeps cast order across languages).
pub fn store_localized(
    pool: &Pool,
    kind: &str,
    id: &str,
    core_meta: &Metadata,
    by_lang: &HashMap<String, Metadata>,
) -> Result<()> {
    use super::metadata_core::{self, MetaCore};
    use super::translations::{self, TransData};
    let conn = pool.get()?;
    let core = MetaCore {
        // `Metadata::tmdb_id` is 0 when unresolved; store NULL for that.
        tmdb_id: (core_meta.tmdb_id != 0).then_some(core_meta.tmdb_id),
        imdb_id: core_meta.imdb_id.clone(),
        tvdb_id: core_meta.tvdb_id,
        release_date: core_meta.release_date.clone(),
        rating: core_meta.rating,
        poster_url: core_meta.poster_url.clone(),
        backdrop_url: core_meta.backdrop_url.clone(),
        logo_url: core_meta.logo_url.clone(),
        cast: core_meta.cast.clone(),
        crew: core_meta.crew.clone(),
    };
    metadata_core::write_core(&conn, kind, id, &core)?;
    for (lang, m) in by_lang {
        let data = TransData {
            title: m.title.clone(),
            tagline: m.tagline.clone(),
            overview: m.overview.clone(),
            genres: m.genres.clone(),
            characters: m.cast.iter().map(|c| c.character.clone()).collect(),
            reason: None,
        };
        if !data.is_empty() {
            translations::write(&conn, kind, id, lang, translations::TMDB, &data)?;
        }
    }
    Ok(())
}

/// Wipes all resolved TMDB metadata so the next enrichment starts from
/// scratch. Returns `(items_cleared, shows_cleared)`; the caller must also
/// clear the process-wide lookup cache (`crate::infra::metadata::Cache`).
pub fn reset_all_metadata(pool: &Pool) -> Result<(usize, usize)> {
    let conn = pool.get()?;
    let items = conn.execute("UPDATE items SET metadata = NULL WHERE metadata IS NOT NULL", [])?;
    let shows = conn.execute("UPDATE shows SET metadata = NULL WHERE metadata IS NOT NULL", [])?;
    conn.execute("DELETE FROM item_vectors", [])?;
    conn.execute("DELETE FROM season_meta", [])?;
    // LLM-sourced rows are left intact: regenerated by their own jobs, not TMDB enrichment.
    conn.execute("DELETE FROM metadata_core", [])?;
    conn.execute("DELETE FROM translations WHERE source = 'tmdb'", [])?;
    Ok((items, shows))
}

pub fn set_season_cast(pool: &Pool, show_id: &str, season: u32, cast: &[CastMember]) -> Result<()> {
    let conn = pool.get()?;
    let json = serde_json::to_string(cast)?;
    conn.execute(
        "INSERT INTO season_meta (show_id,season,casts) VALUES (?1,?2,?3) \
         ON CONFLICT(show_id,season) DO UPDATE SET casts=excluded.casts",
        params![show_id, season, json],
    )?;
    Ok(())
}

pub fn seasons_with_cast(pool: &Pool, show_id: &str) -> Result<std::collections::HashSet<u32>> {
    let conn = pool.get()?;
    let mut stmt = conn.prepare("SELECT season FROM season_meta WHERE show_id = ?1")?;
    let rows = stmt.query_map(params![show_id], |r| r.get::<_, u32>(0))?;
    Ok(rows.collect::<rusqlite::Result<std::collections::HashSet<_>>>()?)
}

pub fn season_casts(pool: &Pool, show_id: &str) -> Result<HashMap<u32, Vec<CastMember>>> {
    let conn = pool.get()?;
    let mut stmt = conn.prepare("SELECT season,casts FROM season_meta WHERE show_id = ?1")?;
    let rows = stmt.query_map(params![show_id], |r| {
        Ok((r.get::<_, u32>(0)?, r.get::<_, String>(1)?))
    })?;
    let mut out = HashMap::new();
    for row in rows {
        let (season, json) = row?;
        if let Ok(cast) = serde_json::from_str::<Vec<CastMember>>(&json) {
            out.insert(season, cast);
        }
    }
    Ok(out)
}

pub fn set_show_metadata(pool: &Pool, id: &str, meta: &Metadata) -> Result<()> {
    let conn = pool.get()?;
    let json = serde_json::to_string(meta)?;
    conn.execute("UPDATE shows SET metadata = ?2 WHERE id = ?1", params![id, json])?;
    Ok(())
}

/// Rewrites a movie's catalog title from a *trusted* TMDB match (an operator
/// correction or an acquisition-hinted import). Does not touch the file on disk.
pub fn set_item_title(pool: &Pool, id: &str, title: &str) -> Result<()> {
    let conn = pool.get()?;
    conn.execute("UPDATE items SET title = ?2 WHERE id = ?1", params![id, title])?;
    Ok(())
}

/// Rewrites a show's catalog title from a trusted TMDB match. See [`set_item_title`].
pub fn set_show_title(pool: &Pool, id: &str, title: &str) -> Result<()> {
    let conn = pool.get()?;
    conn.execute("UPDATE shows SET title = ?2 WHERE id = ?1", params![id, title])?;
    Ok(())
}

/// (file_id, abs_path, owning item_id) for every file awaiting an ffprobe pass.
pub fn unprobed_files(pool: &Pool) -> Result<Vec<(String, String, String)>> {
    let conn = pool.get()?;
    let mut stmt =
        conn.prepare("SELECT id, abs_path, item_id FROM files WHERE probed = 0")?;
    let rows = stmt.query_map([], |r| {
        Ok((r.get::<_, String>(0)?, r.get::<_, String>(1)?, r.get::<_, String>(2)?))
    })?;
    Ok(rows.collect::<rusqlite::Result<Vec<_>>>()?)
}

/// Item ids that are fully probed (≥1 file, none unprobed).
pub fn probed_item_ids(pool: &Pool) -> Result<std::collections::HashSet<String>> {
    let conn = pool.get()?;
    let mut stmt = conn.prepare(
        "SELECT item_id FROM files GROUP BY item_id \
         HAVING SUM(CASE WHEN probed=0 THEN 1 ELSE 0 END)=0",
    )?;
    let rows = stmt.query_map([], |r| r.get::<_, String>(0))?;
    Ok(rows.collect::<rusqlite::Result<_>>()?)
}

/// Whether every file of an item is probed (and it has at least one).
pub fn item_probed(pool: &Pool, item_id: &str) -> Result<bool> {
    let conn = pool.get()?;
    let (total, unprobed): (i64, i64) = conn.query_row(
        "SELECT COUNT(*), SUM(CASE WHEN probed=0 THEN 1 ELSE 0 END) FROM files WHERE item_id=?1",
        params![item_id],
        |r| Ok((r.get(0)?, r.get::<_, Option<i64>>(1)?.unwrap_or(0))),
    )?;
    Ok(total > 0 && unprobed == 0)
}

pub fn file_ids_for_item(pool: &Pool, item_id: &str) -> Result<Vec<String>> {
    let conn = pool.get()?;
    let mut stmt = conn.prepare("SELECT id FROM files WHERE item_id=?1")?;
    let rows = stmt.query_map(params![item_id], |r| r.get::<_, String>(0))?;
    Ok(rows.collect::<rusqlite::Result<Vec<_>>>()?)
}

pub fn unprobe_item_files(pool: &Pool, item_id: &str) -> Result<()> {
    let conn = pool.get()?;
    conn.execute("UPDATE files SET probed=0 WHERE item_id=?1", params![item_id])?;
    Ok(())
}

/// Clears one subject's derived TMDB rows so a reprocess re-enriches it.
/// Nulling only the metadata blob would leave the old `tmdb_id` and localized
/// text behind, outliving a re-enrichment that resolves to fewer languages.
pub fn clear_subject_metadata(pool: &Pool, kind: &str, id: &str) -> Result<()> {
    let conn = pool.get()?;
    if kind == metadata_core::SHOW {
        conn.execute("UPDATE shows SET metadata=NULL WHERE id=?1", params![id])?;
        conn.execute("DELETE FROM season_meta WHERE show_id=?1", params![id])?;
    } else {
        conn.execute("UPDATE items SET metadata=NULL WHERE id=?1", params![id])?;
        conn.execute("DELETE FROM item_vectors WHERE id=?1", params![id])?;
    }
    metadata_core::delete_core(&conn, kind, id)?;
    translations::delete_all(&conn, kind, id)?;
    Ok(())
}

/// Every file's `(id, "mtime:size")`: a changed file gets a new signature and is
/// re-probed.
pub fn all_file_sigs(pool: &Pool) -> Result<Vec<(String, String)>> {
    let conn = pool.get()?;
    let mut stmt =
        conn.prepare("SELECT id, COALESCE(mtime,0) || ':' || COALESCE(size,0) FROM files")?;
    let rows = stmt.query_map([], |r| Ok((r.get::<_, String>(0)?, r.get::<_, String>(1)?)))?;
    Ok(rows.collect::<rusqlite::Result<Vec<_>>>()?)
}

/// `(abs_path, item_id, probed)` for one file; `None` if the file row is gone.
pub fn probe_target(pool: &Pool, file_id: &str) -> Result<Option<(String, String, bool)>> {
    let conn = pool.get()?;
    let mut stmt = conn.prepare("SELECT abs_path, item_id, probed FROM files WHERE id=?1")?;
    let mut rows = stmt.query_map(params![file_id], |r| {
        Ok((r.get::<_, String>(0)?, r.get::<_, String>(1)?, r.get::<_, i64>(2)? != 0))
    })?;
    match rows.next() {
        Some(r) => Ok(Some(r?)),
        None => Ok(None),
    }
}

pub fn item_has_probed_file(pool: &Pool, item_id: &str) -> Result<bool> {
    let conn = pool.get()?;
    let n: i64 = conn.query_row(
        "SELECT COUNT(*) FROM files WHERE item_id = ?1 AND probed = 1",
        params![item_id],
        |r| r.get(0),
    )?;
    Ok(n > 0)
}

/// Persists one file's probe result, then recomputes the owning item's representative columns.
pub fn set_file_probe(
    pool: &Pool,
    file_id: &str,
    duration_ms: Option<u64>,
    video: Option<&VideoStream>,
    audio: Option<&AudioStream>,
    audio_tracks: &[AudioStream],
    subtitles: &[SubtitleTrack],
) -> Result<()> {
    let conn = pool.get()?;
    let subs = serde_json::to_string(subtitles).unwrap_or_else(|_| "[]".into());
    let a_tracks = serde_json::to_string(audio_tracks).unwrap_or_else(|_| "[]".into());
    conn.execute(
        "UPDATE files SET probed=1, duration_ms=?2, \
            v_codec=?3, v_width=?4, v_height=?5, v_hdr=?6, v_bit_depth=?7, \
            a_codec=?8, a_channels=?9, a_language=?10, subtitles=?11, audio_tracks=?12 \
         WHERE id = ?1",
        params![
            file_id,
            duration_ms.map(|d| d as i64),
            video.map(|v| v.codec.clone()),
            video.and_then(|v| v.width),
            video.and_then(|v| v.height),
            video.map(|v| v.hdr as i64),
            video.and_then(|v| v.bit_depth),
            audio.map(|a| a.codec.clone()),
            audio.and_then(|a| a.channels),
            audio.and_then(|a| a.language.clone()),
            subs,
            a_tracks,
        ],
    )?;

    let item_id: Option<String> = conn
        .query_row("SELECT item_id FROM files WHERE id = ?1", params![file_id], |r| r.get(0))
        .ok();
    if let Some(item_id) = item_id {
        recompute_item_representative(&conn, &item_id)?;
    }
    Ok(())
}

fn recompute_item_representative(conn: &Connection, item_id: &str) -> Result<()> {
    let best: Option<(String, String, Option<String>, Option<i64>)> = conn
        .query_row(
            "SELECT abs_path, container, rel_path, duration_ms FROM files \
             WHERE item_id = ?1 AND probed = 1 \
             ORDER BY v_width DESC NULLS LAST, id LIMIT 1",
            params![item_id],
            |r| {
                Ok((
                    r.get::<_, String>(0)?,
                    r.get::<_, String>(1)?,
                    r.get::<_, Option<String>>(2)?,
                    r.get::<_, Option<i64>>(3)?,
                ))
            },
        )
        .ok();

    if let Some((abs, container, rel, duration)) = best {
        conn.execute(
            "UPDATE items SET container=?2, abs_path=?3, rel_path=?4, duration_ms=?5 WHERE id=?1",
            params![item_id, container, abs, rel, duration],
        )?;
    }
    Ok(())
}

fn recompute_all_representatives(pool: &Pool) -> Result<()> {
    let conn = pool.get()?;
    let mut stmt = conn.prepare(
        "SELECT DISTINCT item_id FROM files WHERE probed = 1",
    )?;
    let ids: Vec<String> = stmt
        .query_map([], |r| r.get::<_, String>(0))?
        .collect::<rusqlite::Result<Vec<_>>>()?;
    for id in ids {
        recompute_item_representative(&conn, &id)?;
    }
    Ok(())
}

/// Diff-syncs the scanned index into the DB in one transaction: preserves
/// `items.metadata`/`shows.metadata` and a file's probed data when its
/// `size`+`mtime` are unchanged, unlike a blunt DELETE-all + INSERT.
pub fn sync_all(
    pool: &Pool,
    libraries: &[Library],
    shows: &[Show],
    items: &[MediaItem],
    mtimes: &HashMap<String, Option<i64>>,
) -> Result<()> {
    let mut conn = pool.get()?;
    let tx = conn.transaction()?;

    sync_libraries(&tx, libraries)?;
    sync_shows(&tx, shows)?;
    sync_items(&tx, items)?;
    sync_files(&tx, items, mtimes)?;
    prune_orphans(&tx)?;

    tx.commit()?;

    recompute_all_representatives(pool)?;
    let _ = prune_orphan_vectors(pool);
    Ok(())
}

    // Upserts by id, then deletes only libraries no longer scanned: a wholesale
    // DELETE FROM libraries would cascade to items/files and wipe what this sync preserves.
fn sync_libraries(tx: &rusqlite::Transaction, libraries: &[Library]) -> Result<()> {
    let mut lib_stmt = tx.prepare(
        "INSERT INTO libraries (id,name,kind,path,added_at) VALUES (?1,?2,?3,?4,?5) \
         ON CONFLICT(id) DO UPDATE SET name=excluded.name, kind=excluded.kind, path=excluded.path",
    )?;
    for l in libraries {
        lib_stmt.execute(params![l.id, l.name, library_kind_str(&l.kind), l.path, now_or_blank()])?;
    }
    let keep: Vec<String> = libraries.iter().map(|l| l.id.clone()).collect();
    let mut existing: Vec<String> = Vec::new();
    {
        let mut q = tx.prepare("SELECT id FROM libraries")?;
        let rows = q.query_map([], |r| r.get::<_, String>(0))?;
        for r in rows {
            existing.push(r?);
        }
    }
    let mut del = tx.prepare("DELETE FROM libraries WHERE id = ?1")?;
    for id in &existing {
        if !keep.contains(id) {
            del.execute(params![id])?;
        }
    }
    Ok(())
}

fn sync_shows(tx: &rusqlite::Transaction, shows: &[Show]) -> Result<()> {
    let mut show_stmt = tx.prepare(
        "INSERT INTO shows (id,library,title,year,added_at) VALUES (?1,?2,?3,?4,?5) \
         ON CONFLICT(id) DO UPDATE SET library=excluded.library, title=excluded.title, \
             year=COALESCE(excluded.year, shows.year)",
    )?;
    for s in shows {
        show_stmt.execute(params![s.id, s.library, s.title, s.year, s.added_at])?;
    }
    Ok(())
}

fn sync_items(tx: &rusqlite::Transaction, items: &[MediaItem]) -> Result<()> {
    let mut item_stmt = tx.prepare(
        "INSERT INTO items \
            (id,kind,title,year,container,library,show_id,show_title,\
             season,episode,episode_end,episode_title,rel_path,abs_path,added_at) \
         VALUES (?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11,?12,?13,?14,?15) \
         ON CONFLICT(id) DO UPDATE SET \
             kind=excluded.kind, title=excluded.title, year=excluded.year, \
             library=excluded.library, show_id=excluded.show_id, \
             show_title=excluded.show_title, season=excluded.season, \
             episode=excluded.episode, episode_end=excluded.episode_end, \
             episode_title=excluded.episode_title",
    )?;
    for i in items {
        // Seed representative columns from the first file; probing recomputes them.
        let seed = i.files.first();
        let container = seed.map(|f| f.container.clone()).unwrap_or_default();
        let rel_path = seed.and_then(|f| f.rel_path.clone());
        let abs_path = seed.and_then(|f| f.abs_path.clone());
        item_stmt.execute(params![
            i.id,
            kind_str(&i.kind),
            i.title,
            i.year,
            container,
            i.library,
            i.show_id,
            i.show_title,
            i.season,
            i.episode,
            i.episode_end,
            i.episode_title,
            rel_path,
            abs_path,
            i.added_at,
        ])?;
    }
    Ok(())
}

fn sync_files(
    tx: &rusqlite::Transaction,
    items: &[MediaItem],
    mtimes: &HashMap<String, Option<i64>>,
) -> Result<()> {
    let scanned: std::collections::HashSet<&str> = items
        .iter()
        .flat_map(|i| i.files.iter())
        .filter_map(|f| f.abs_path.as_deref())
        .collect();

    delete_gone_files(tx, &scanned)?;
    let prev = existing_file_sigs(tx)?;

    let mut keep_stmt = tx.prepare(
        "INSERT INTO files (id,item_id,abs_path,rel_path,container,size,mtime,edition) \
         VALUES (?1,?2,?3,?4,?5,?6,?7,?8) \
         ON CONFLICT(abs_path) DO UPDATE SET \
             id=excluded.id, item_id=excluded.item_id, rel_path=excluded.rel_path, \
             container=excluded.container, size=excluded.size, mtime=excluded.mtime, \
             edition=excluded.edition",
    )?;
    let mut reset_stmt = tx.prepare(
        "INSERT INTO files (id,item_id,abs_path,rel_path,container,size,mtime,edition,probed,\
             duration_ms,v_codec,v_width,v_height,v_hdr,v_bit_depth,a_codec,a_channels,a_language,subtitles,audio_tracks) \
         VALUES (?1,?2,?3,?4,?5,?6,?7,?8,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'[]','[]') \
         ON CONFLICT(abs_path) DO UPDATE SET \
             id=excluded.id, item_id=excluded.item_id, rel_path=excluded.rel_path, \
             container=excluded.container, size=excluded.size, mtime=excluded.mtime, \
             edition=excluded.edition, probed=0, duration_ms=NULL, v_codec=NULL, v_width=NULL, \
             v_height=NULL, v_hdr=NULL, v_bit_depth=NULL, a_codec=NULL, a_channels=NULL, \
             a_language=NULL, subtitles='[]', audio_tracks='[]'",
    )?;
    // Pre-probed files (demo/seed content) skip the phase-2 probe pass.
    let mut preprobed_stmt = tx.prepare(
        "INSERT INTO files (id,item_id,abs_path,rel_path,container,size,mtime,edition,probed,\
             duration_ms,v_codec,v_width,v_height,v_hdr,v_bit_depth,a_codec,a_channels,a_language,subtitles,audio_tracks) \
         VALUES (?1,?2,?3,?4,?5,?6,?7,?8,1,?9,?10,?11,?12,?13,?14,?15,?16,?17,?18,?19) \
         ON CONFLICT(abs_path) DO UPDATE SET \
             id=excluded.id, item_id=excluded.item_id, rel_path=excluded.rel_path, \
             container=excluded.container, size=excluded.size, mtime=excluded.mtime, \
             edition=excluded.edition, probed=1, duration_ms=excluded.duration_ms, \
             v_codec=excluded.v_codec, v_width=excluded.v_width, v_height=excluded.v_height, \
             v_hdr=excluded.v_hdr, v_bit_depth=excluded.v_bit_depth, a_codec=excluded.a_codec, \
             a_channels=excluded.a_channels, a_language=excluded.a_language, subtitles=excluded.subtitles, \
             audio_tracks=excluded.audio_tracks",
    )?;

    for i in items {
        for f in &i.files {
            upsert_scanned_file(
                &mut keep_stmt,
                &mut reset_stmt,
                &mut preprobed_stmt,
                &prev,
                mtimes,
                i,
                f,
            )?;
        }
    }
    Ok(())
}

fn delete_gone_files(
    tx: &rusqlite::Transaction,
    scanned: &std::collections::HashSet<&str>,
) -> Result<()> {
    let mut existing: Vec<(String, String)> = Vec::new();
    {
        let mut q = tx.prepare("SELECT id, abs_path FROM files")?;
        let rows = q.query_map([], |r| Ok((r.get::<_, String>(0)?, r.get::<_, String>(1)?)))?;
        for r in rows {
            existing.push(r?);
        }
    }
    let mut del = tx.prepare("DELETE FROM files WHERE id = ?1")?;
    for (id, abs) in &existing {
        if !scanned.contains(abs.as_str()) {
            del.execute(params![id])?;
        }
    }
    Ok(())
}

fn existing_file_sigs(
    tx: &rusqlite::Transaction,
) -> Result<HashMap<String, (Option<i64>, Option<i64>, i64)>> {
    let mut prev: HashMap<String, (Option<i64>, Option<i64>, i64)> = HashMap::new();
    let mut q = tx.prepare("SELECT abs_path, size, mtime, probed FROM files")?;
    let rows = q.query_map([], |r| {
        Ok((
            r.get::<_, String>(0)?,
            r.get::<_, Option<i64>>(1)?,
            r.get::<_, Option<i64>>(2)?,
            r.get::<_, i64>(3)?,
        ))
    })?;
    for r in rows {
        let (abs, size, mtime, probed) = r?;
        prev.insert(abs, (size, mtime, probed));
    }
    Ok(prev)
}

fn upsert_scanned_file<'a>(
    keep_stmt: &mut rusqlite::Statement<'a>,
    reset_stmt: &mut rusqlite::Statement<'a>,
    preprobed_stmt: &mut rusqlite::Statement<'a>,
    prev: &HashMap<String, (Option<i64>, Option<i64>, i64)>,
    mtimes: &HashMap<String, Option<i64>>,
    i: &MediaItem,
    f: &MediaFile,
) -> Result<()> {
    let Some(abs) = f.abs_path.as_deref() else { return Ok(()) };
    let size = f.size.map(|s| s as i64);
    let mtime = mtimes.get(&f.id).copied().flatten();

    if f.probed {
        let v = f.video.as_ref();
        let a = f.audio.as_ref();
        let subs = serde_json::to_string(&f.subtitles).unwrap_or_else(|_| "[]".into());
        let a_tracks = serde_json::to_string(&f.audio_tracks).unwrap_or_else(|_| "[]".into());
        preprobed_stmt.execute(params![
            f.id, i.id, abs, f.rel_path, f.container, size, mtime, f.edition,
            f.duration_ms.map(|d| d as i64),
            v.map(|v| v.codec.clone()),
            v.and_then(|v| v.width),
            v.and_then(|v| v.height),
            v.map(|v| v.hdr as i64),
            v.and_then(|v| v.bit_depth),
            a.map(|a| a.codec.clone()),
            a.and_then(|a| a.channels),
            a.and_then(|a| a.language.clone()),
            subs,
            a_tracks,
        ])?;
        return Ok(());
    }

    let unchanged_probed = prev.get(abs).is_some_and(|(psize, pmtime, probed)| {
        *probed == 1 && *psize == size && *pmtime == mtime
    });
    let stmt = if unchanged_probed { keep_stmt } else { reset_stmt };
    stmt.execute(params![
        f.id, i.id, abs, f.rel_path, f.container, size, mtime, f.edition,
    ])?;
    Ok(())
}

    // Prunes items/shows with no backing files, then the language-cache rows for
    // vanished titles (no FK on those tables, so the item/show cascade misses them).
fn prune_orphans(tx: &rusqlite::Transaction) -> Result<()> {
    tx.execute("DELETE FROM items WHERE id NOT IN (SELECT DISTINCT item_id FROM files)", [])?;
    tx.execute("DELETE FROM shows WHERE id NOT IN (SELECT DISTINCT show_id FROM items WHERE show_id IS NOT NULL)", [])?;

    tx.execute(
        "DELETE FROM metadata_core WHERE \
            (subject_kind='item' AND subject_id NOT IN (SELECT id FROM items)) OR \
            (subject_kind='show' AND subject_id NOT IN (SELECT id FROM shows))",
        [],
    )?;
    tx.execute(
        "DELETE FROM translations WHERE subject_kind IN ('item','episode') \
            AND subject_id NOT IN (SELECT id FROM items)",
        [],
    )?;
    tx.execute(
        "DELETE FROM translations WHERE subject_kind='show' \
            AND subject_id NOT IN (SELECT id FROM shows)",
        [],
    )?;
    tx.execute(
        "DELETE FROM translations WHERE subject_kind='season_cast' \
            AND substr(subject_id, 1, instr(subject_id, ':') - 1) NOT IN (SELECT id FROM shows)",
        [],
    )?;
    Ok(())
}

fn kind_str(k: &Kind) -> &'static str {
    match k {
        Kind::Movie => "movie",
        Kind::Episode => "episode",
        Kind::Video => "video",
    }
}

fn library_kind_str(k: &LibraryKind) -> &'static str {
    match k {
        LibraryKind::Movies => "movies",
        LibraryKind::Shows => "shows",
        LibraryKind::Mixed => "mixed",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use kroma_domain::{Kind, MediaFile, MediaItem, VideoStream};
    use std::collections::HashMap;
    use std::sync::atomic::{AtomicU32, Ordering};

    static SEQ: AtomicU32 = AtomicU32::new(0);

    fn pool() -> Pool {
        let n = SEQ.fetch_add(1, Ordering::Relaxed);
        let path = std::env::temp_dir().join(format!("kroma-ingest-{}-{n}.db", std::process::id()));
        let _ = std::fs::remove_file(&path);
        crate::init(&path).unwrap()
    }

    fn video() -> VideoStream {
        VideoStream { codec: "hevc".into(), width: Some(3840), height: Some(2160), hdr: false, bit_depth: Some(10) }
    }

    fn lib(id: &str) -> Library {
        Library { id: id.into(), name: "L".into(), kind: LibraryKind::Movies, path: "/x".into(), item_count: 0 }
    }

    fn file(id: &str, abs: &str, probed: bool) -> MediaFile {
        MediaFile {
            id: id.into(),
            rel_path: Some(format!("{id}.mkv")),
            container: "mkv".into(),
            duration_ms: if probed { Some(7_200_000) } else { None },
            video: if probed { Some(video()) } else { None },
            audio: None,
            audio_tracks: Vec::new(),
            subtitles: Vec::new(),
            size: Some(1000),
            edition: None,
            probed,
            abs_path: Some(abs.into()),
        }
    }

    fn movie(id: &str, title: &str, library: &str, files: Vec<MediaFile>) -> MediaItem {
        MediaItem {
            id: id.into(),
            title: title.into(),
            kind: Kind::Movie,
            year: Some(2021),
            duration_ms: None,
            container: String::new(),
            video: None,
            audio: None,
            audio_tracks: Vec::new(),
            subtitles: Vec::new(),
            library: library.into(),
            show_id: None,
            show_title: None,
            season: None,
            episode: None,
            episode_end: None,
            episode_title: None,
            rel_path: None,
            added_at: "t".into(),
            metadata: None,
            abs_path: None,
            files,
            default_file_id: None,
            markers: Vec::new(),
            audio_analysis: None,
        }
    }

    fn mtimes_of(items: &[MediaItem], mtime: i64) -> HashMap<String, Option<i64>> {
        items
            .iter()
            .flat_map(|i| i.files.iter())
            .map(|f| (f.id.clone(), Some(mtime)))
            .collect()
    }

    fn meta(tmdb: u64, title: &str) -> Metadata {
        Metadata {
            provider: "tmdb",
            tmdb_id: tmdb,
            imdb_id: Some("tt1".into()),
            title: Some(title.into()),
            tagline: None,
            overview: Some("an overview".into()),
            release_date: Some("2021-01-01".into()),
            genres: vec!["Science Fiction".into()],
            rating: Some(8.0),
            poster_url: Some("/api/images/p.webp".into()),
            backdrop_url: None,
            logo_url: None,
            theme_url: None,
            cast: vec![CastMember { name: "Timothee".into(), character: Some("Paul".into()), profile_url: None }],
            crew: vec![],
            keywords: vec![],
            tvdb_id: None,
            tmdb_url: "https://tmdb/1".into(),
        }
    }

    #[test]
    fn sync_all_creates_updates_and_prunes() {
        let p = pool();
        let items = vec![
            movie("m1", "Dune", "lib", vec![file("f1", "/media/m1.mkv", false)]),
            movie("m2", "Arrival", "lib", vec![file("f2", "/media/m2.mkv", false)]),
        ];
        sync_all(&p, &[lib("lib")], &[], &items, &mtimes_of(&items, 100)).unwrap();
        assert_eq!(crate::counts(&p).unwrap(), (1, 2, 0));
        let got = crate::get_item(&p, "m1").unwrap().unwrap();
        assert_eq!(got.files.len(), 1);
        assert_eq!(got.container, "mkv"); // seeded from the file until a probe recomputes

        let mut unprobed = unprobed_files(&p).unwrap();
        unprobed.sort();
        assert_eq!(unprobed.len(), 2);
        assert!(unprobed.iter().any(|(id, abs, item)| id == "f1" && abs == "/media/m1.mkv" && item == "m1"));

        let items = vec![movie("m1", "Dune", "lib", vec![file("f1", "/media/m1.mkv", false)])];
        sync_all(&p, &[lib("lib")], &[], &items, &mtimes_of(&items, 100)).unwrap();
        assert_eq!(crate::counts(&p).unwrap(), (1, 1, 0));
        assert!(crate::get_item(&p, "m2").unwrap().is_none());
    }

    #[test]
    fn sync_preserves_metadata_and_probe_across_rescans() {
        let p = pool();
        let items = vec![movie("m1", "Dune", "lib", vec![file("f1", "/media/m1.mkv", false)])];
        sync_all(&p, &[lib("lib")], &[], &items, &mtimes_of(&items, 100)).unwrap();

        set_file_probe(&p, "f1", Some(7_200_000), Some(&video()), None, &[], &[]).unwrap();
        set_item_metadata(&p, "m1", &meta(603, "Dune")).unwrap();
        assert!(item_has_probed_file(&p, "m1").unwrap());

        sync_all(&p, &[lib("lib")], &[], &items, &mtimes_of(&items, 100)).unwrap();
        assert!(item_probed(&p, "m1").unwrap(), "unchanged file keeps probed=1");
        let got = crate::get_item(&p, "m1").unwrap().unwrap();
        assert_eq!(got.metadata.as_ref().map(|m| m.tmdb_id), Some(603));

        sync_all(&p, &[lib("lib")], &[], &items, &mtimes_of(&items, 999)).unwrap();
        assert!(!item_probed(&p, "m1").unwrap(), "changed file resets probed=0");
        assert!(crate::get_item(&p, "m1").unwrap().unwrap().metadata.is_some());
    }

    #[test]
    fn sync_preprobed_file_stores_streams_directly() {
        let p = pool();
        let items = vec![movie("m1", "Demo", "lib", vec![file("f1", "demo://m1", true)])];
        sync_all(&p, &[lib("lib")], &[], &items, &mtimes_of(&items, 100)).unwrap();
        assert!(item_has_probed_file(&p, "m1").unwrap());
        assert!(unprobed_files(&p).unwrap().is_empty());
        let got = crate::get_item(&p, "m1").unwrap().unwrap();
        assert_eq!(got.video.map(|v| v.codec), Some("hevc".to_string()));
        // demo:// paths are not streamable, so abs_path stays cleared.
        assert!(got.abs_path.is_none());
    }

    #[test]
    fn probe_helpers_over_seeded_files() {
        let p = pool();
        {
            let conn = p.get().unwrap();
            conn.execute(
                "INSERT INTO libraries (id,name,kind,path,added_at) VALUES ('lib','L','movies','/x','t')",
                [],
            )
            .unwrap();
            for id in ["m1", "m2"] {
                conn.execute(
                    "INSERT INTO items (id,kind,title,container,library,added_at) VALUES (?1,'movie','T','mkv','lib','t')",
                    params![id],
                )
                .unwrap();
            }
            // m1: one probed + one unprobed (not fully probed).
            conn.execute(
                "INSERT INTO files (id,item_id,abs_path,container,probed,mtime,size) VALUES ('f1','m1','/a',' ',1,100,2000)",
                [],
            )
            .unwrap();
            conn.execute(
                "INSERT INTO files (id,item_id,abs_path,container,probed) VALUES ('f2','m1','/b','',0)",
                [],
            )
            .unwrap();
            // m2: a single probed file (fully probed).
            conn.execute(
                "INSERT INTO files (id,item_id,abs_path,container,probed) VALUES ('f3','m2','/c','',1)",
                [],
            )
            .unwrap();
        }

        assert!(!item_probed(&p, "m1").unwrap());
        assert!(item_probed(&p, "m2").unwrap());
        assert!(!item_probed(&p, "missing").unwrap());

        let fully = probed_item_ids(&p).unwrap();
        assert!(fully.contains("m2") && !fully.contains("m1"));

        let mut ids = file_ids_for_item(&p, "m1").unwrap();
        ids.sort();
        assert_eq!(ids, vec!["f1".to_string(), "f2".to_string()]);

        assert_eq!(probe_target(&p, "f1").unwrap(), Some(("/a".to_string(), "m1".to_string(), true)));
        assert!(probe_target(&p, "gone").unwrap().is_none());
        let sigs: HashMap<String, String> = all_file_sigs(&p).unwrap().into_iter().collect();
        assert_eq!(sigs.get("f1").map(String::as_str), Some("100:2000"));
        assert_eq!(sigs.get("f3").map(String::as_str), Some("0:0")); // null mtime/size

        unprobe_item_files(&p, "m1").unwrap();
        assert!(!item_has_probed_file(&p, "m1").unwrap());
    }

    #[test]
    fn metadata_write_localized_and_reset() {
        let p = pool();
        {
            let conn = p.get().unwrap();
            conn.execute(
                "INSERT INTO libraries (id,name,kind,path,added_at) VALUES ('lib','L','movies','/x','t')",
                [],
            )
            .unwrap();
            conn.execute(
                "INSERT INTO items (id,kind,title,container,library,added_at) VALUES ('m1','movie','Dune','mkv','lib','t')",
                [],
            )
            .unwrap();
            conn.execute(
                "INSERT INTO shows (id,library,title,added_at) VALUES ('s1','lib','Show','t')",
                [],
            )
            .unwrap();
        }
        set_item_metadata(&p, "m1", &meta(603, "Dune")).unwrap();
        set_show_metadata(&p, "s1", &meta(1396, "Show")).unwrap();

        let mut by_lang = HashMap::new();
        by_lang.insert("fr".to_string(), meta(603, "Dune VF"));
        store_localized(&p, crate::metadata_core::ITEM, "m1", &meta(603, "Dune"), &by_lang).unwrap();
        let core = crate::metadata_core::get_core(&p, "item", "m1").unwrap().unwrap();
        assert_eq!(core.tmdb_id, Some(603));
        // Character names are stripped from the invariant core (they live per-lang).
        assert_eq!(core.cast.len(), 1);
        assert!(core.cast[0].character.is_none());
        let fr = crate::translations::resolve_one(&p, "item", "m1", "fr").unwrap().unwrap();
        assert_eq!(fr.title.as_deref(), Some("Dune VF"));
        assert_eq!(fr.characters, vec![Some("Paul".to_string())]);

        let (items_cleared, shows_cleared) = reset_all_metadata(&p).unwrap();
        assert_eq!((items_cleared, shows_cleared), (1, 1));
        assert!(crate::get_item(&p, "m1").unwrap().unwrap().metadata.is_none());
        assert!(crate::metadata_core::get_core(&p, "item", "m1").unwrap().is_none());
        assert!(crate::translations::resolve_one(&p, "item", "m1", "fr").unwrap().is_none());
    }

    #[test]
    fn set_item_and_show_title_rename_the_catalog_row() {
        let p = pool();
        {
            let conn = p.get().unwrap();
            conn.execute(
                "INSERT INTO libraries (id,name,kind,path,added_at) VALUES ('lib','L','movies','/x','t')",
                [],
            )
            .unwrap();
            conn.execute(
                "INSERT INTO items (id,kind,title,container,library,added_at) VALUES ('m1','movie','2001','mkv','lib','t')",
                [],
            )
            .unwrap();
            conn.execute(
                "INSERT INTO shows (id,library,title,added_at) VALUES ('s1','lib','Show','t')",
                [],
            )
            .unwrap();
        }
        set_item_title(&p, "m1", "2001: A Space Odyssey").unwrap();
        set_show_title(&p, "s1", "Severance").unwrap();
        assert_eq!(crate::get_item(&p, "m1").unwrap().unwrap().title, "2001: A Space Odyssey");
        let show_title: String = p
            .get()
            .unwrap()
            .query_row("SELECT title FROM shows WHERE id = 's1'", [], |r| r.get(0))
            .unwrap();
        assert_eq!(show_title, "Severance");
    }

    #[test]
    fn season_cast_and_clear_metadata() {
        let p = pool();
        {
            let conn = p.get().unwrap();
            conn.execute(
                "INSERT INTO libraries (id,name,kind,path,added_at) VALUES ('lib','L','shows','/x','t')",
                [],
            )
            .unwrap();
            conn.execute(
                "INSERT INTO items (id,kind,title,container,library,added_at) VALUES ('m1','movie','Dune','mkv','lib','t')",
                [],
            )
            .unwrap();
            conn.execute(
                "INSERT INTO shows (id,library,title,added_at) VALUES ('s1','lib','Show','t')",
                [],
            )
            .unwrap();
        }
        assert!(seasons_with_cast(&p, "s1").unwrap().is_empty());
        let cast = vec![CastMember { name: "Adam".into(), character: Some("Mark".into()), profile_url: None }];
        set_season_cast(&p, "s1", 1, &cast).unwrap();
        set_season_cast(&p, "s1", 2, &cast).unwrap();
        set_season_cast(&p, "s1", 1, &cast).unwrap(); // idempotent upsert
        let mut seasons: Vec<u32> = seasons_with_cast(&p, "s1").unwrap().into_iter().collect();
        seasons.sort_unstable();
        assert_eq!(seasons, vec![1, 2]);
        let casts = season_casts(&p, "s1").unwrap();
        assert_eq!(casts.len(), 2);
        assert_eq!(casts[&1][0].name, "Adam");

        set_item_metadata(&p, "m1", &meta(603, "Dune")).unwrap();
        set_show_metadata(&p, "s1", &meta(1396, "Show")).unwrap();
        store_localized(&p, metadata_core::ITEM, "m1", &meta(603, "Dune"), &HashMap::new()).unwrap();
        crate::set_item_vector(&p, "m1", &[0.5, 0.5]).unwrap();
        clear_subject_metadata(&p, metadata_core::ITEM, "m1").unwrap();
        clear_subject_metadata(&p, metadata_core::SHOW, "s1").unwrap();
        assert!(crate::get_item(&p, "m1").unwrap().unwrap().metadata.is_none());
        assert!(crate::get_show(&p, "s1").unwrap().unwrap().show.metadata.is_none());
        assert!(metadata_core::get_core(&p, metadata_core::ITEM, "m1").unwrap().is_none());
        assert!(!crate::has_vector(&p, "m1").unwrap());
        assert!(seasons_with_cast(&p, "s1").unwrap().is_empty());
    }
}
