//! Attaching resolved metadata to a catalog row, and clearing it again.

use std::collections::HashMap;

use anyhow::Result;
use rusqlite::params;

use kroma_domain::{CastMember, Metadata};

use crate::metadata_core::{self, MetaCore};
use crate::translations::{self, TransData};
use crate::Pool;

pub fn set_item_metadata(pool: &Pool, id: &str, meta: &Metadata) -> Result<()> {
    let conn = pool.get()?;
    let json = serde_json::to_string(meta)?;
    conn.execute("UPDATE items SET metadata = ?2 WHERE id = ?1", params![id, json])?;
    Ok(())
}

/// Dual-writes one subject's metadata: a language-agnostic [`metadata_core`]
/// row plus a [`translations`] row per language. Character names align by
/// index to `core_meta`'s cast (TMDB keeps cast order across languages).
pub fn store_localized(
    pool: &Pool,
    kind: &str,
    id: &str,
    core_meta: &Metadata,
    by_lang: &HashMap<String, Metadata>,
) -> Result<()> {
    let conn = pool.get()?;
    let core = MetaCore {
        // `Metadata::tmdb_id` is 0 when unresolved; store NULL for that.
        tmdb_id: (core_meta.tmdb_id != 0).then_some(core_meta.tmdb_id),
        imdb_id: core_meta.imdb_id.clone(),
        tvdb_id: core_meta.tvdb_id,
        release_date: core_meta.release_date.clone(),
        rating: core_meta.rating,
        poster_url: core_meta.poster_url.clone(),
        backdrop_url: core_meta.backdrop_url.clone(),
        logo_url: core_meta.logo_url.clone(),
        cast: core_meta.cast.clone(),
        crew: core_meta.crew.clone(),
    };
    metadata_core::write_core(&conn, kind, id, &core)?;
    for (lang, m) in by_lang {
        let data = TransData {
            title: m.title.clone(),
            tagline: m.tagline.clone(),
            overview: m.overview.clone(),
            genres: m.genres.clone(),
            characters: m.cast.iter().map(|c| c.character.clone()).collect(),
            reason: None,
        };
        if !data.is_empty() {
            translations::write(&conn, kind, id, lang, translations::TMDB, &data)?;
        }
    }
    Ok(())
}

/// Wipes all resolved TMDB metadata so the next enrichment starts from
/// scratch. Returns `(items_cleared, shows_cleared)`; the caller must also
/// clear the process-wide lookup cache (`crate::infra::metadata::Cache`).
pub fn reset_all_metadata(pool: &Pool) -> Result<(usize, usize)> {
    let mut conn = pool.get()?;
    let tx = conn.transaction()?;
    let items = tx.execute("UPDATE items SET metadata = NULL WHERE metadata IS NOT NULL", [])?;
    let shows = tx.execute("UPDATE shows SET metadata = NULL WHERE metadata IS NOT NULL", [])?;
    tx.execute("DELETE FROM item_vectors", [])?;
    tx.execute("DELETE FROM season_meta", [])?;
    // LLM-sourced rows are left intact: regenerated by their own jobs, not TMDB enrichment.
    tx.execute("DELETE FROM metadata_core", [])?;
    tx.execute("DELETE FROM translations WHERE source = 'tmdb'", [])?;
    tx.commit()?;
    Ok((items, shows))
}

pub fn set_season_cast(pool: &Pool, show_id: &str, season: u32, cast: &[CastMember]) -> Result<()> {
    let conn = pool.get()?;
    let json = serde_json::to_string(cast)?;
    conn.execute(
        "INSERT INTO season_meta (show_id,season,casts) VALUES (?1,?2,?3) \
         ON CONFLICT(show_id,season) DO UPDATE SET casts=excluded.casts",
        params![show_id, season, json],
    )?;
    Ok(())
}

pub fn seasons_with_cast(pool: &Pool, show_id: &str) -> Result<std::collections::HashSet<u32>> {
    let conn = pool.get()?;
    let mut stmt = conn.prepare("SELECT season FROM season_meta WHERE show_id = ?1")?;
    let rows = stmt.query_map(params![show_id], |r| r.get::<_, u32>(0))?;
    Ok(rows.collect::<rusqlite::Result<std::collections::HashSet<_>>>()?)
}

pub fn season_casts(pool: &Pool, show_id: &str) -> Result<HashMap<u32, Vec<CastMember>>> {
    let conn = pool.get()?;
    let mut stmt = conn.prepare("SELECT season,casts FROM season_meta WHERE show_id = ?1")?;
    let rows = stmt.query_map(params![show_id], |r| {
        Ok((r.get::<_, u32>(0)?, r.get::<_, String>(1)?))
    })?;
    let mut out = HashMap::new();
    for row in rows {
        let (season, json) = row?;
        if let Ok(cast) = serde_json::from_str::<Vec<CastMember>>(&json) {
            out.insert(season, cast);
        }
    }
    Ok(out)
}

pub fn set_show_metadata(pool: &Pool, id: &str, meta: &Metadata) -> Result<()> {
    let conn = pool.get()?;
    let json = serde_json::to_string(meta)?;
    conn.execute("UPDATE shows SET metadata = ?2 WHERE id = ?1", params![id, json])?;
    Ok(())
}

/// Rewrites a movie's catalog title from a *trusted* TMDB match (an operator
/// correction or an acquisition-hinted import). Does not touch the file on disk.
pub fn set_item_title(pool: &Pool, id: &str, title: &str) -> Result<()> {
    let conn = pool.get()?;
    conn.execute("UPDATE items SET title = ?2 WHERE id = ?1", params![id, title])?;
    Ok(())
}

/// Rewrites a show's catalog title from a trusted TMDB match. See [`set_item_title`].
pub fn set_show_title(pool: &Pool, id: &str, title: &str) -> Result<()> {
    let conn = pool.get()?;
    conn.execute("UPDATE shows SET title = ?2 WHERE id = ?1", params![id, title])?;
    Ok(())
}

/// Clears one subject's derived TMDB rows so a reprocess re-enriches it.
/// Nulling only the metadata blob would leave the old `tmdb_id` and localized
/// text behind, outliving a re-enrichment that resolves to fewer languages.
pub fn clear_subject_metadata(pool: &Pool, kind: &str, id: &str) -> Result<()> {
    let mut conn = pool.get()?;
    let tx = conn.transaction()?;
    if kind == metadata_core::SHOW {
        tx.execute("UPDATE shows SET metadata=NULL WHERE id=?1", params![id])?;
        tx.execute("DELETE FROM season_meta WHERE show_id=?1", params![id])?;
    } else {
        tx.execute("UPDATE items SET metadata=NULL WHERE id=?1", params![id])?;
        tx.execute("DELETE FROM item_vectors WHERE id=?1", params![id])?;
    }
    metadata_core::delete_core(&tx, kind, id)?;
    translations::delete_all(&tx, kind, id)?;
    tx.commit()?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ingest::test_support::*;

    #[test]
    fn metadata_write_localized_and_reset() {
        let p = pool();
        {
            let conn = p.get().unwrap();
            conn.execute(
                "INSERT INTO libraries (id,name,kind,path,added_at) VALUES ('lib','L','movies','/x','t')",
                [],
            )
            .unwrap();
            conn.execute(
                "INSERT INTO items (id,kind,title,container,library,added_at) VALUES ('m1','movie','Dune','mkv','lib','t')",
                [],
            )
            .unwrap();
            conn.execute(
                "INSERT INTO shows (id,library,title,added_at) VALUES ('s1','lib','Show','t')",
                [],
            )
            .unwrap();
        }
        set_item_metadata(&p, "m1", &meta(603, "Dune")).unwrap();
        set_show_metadata(&p, "s1", &meta(1396, "Show")).unwrap();

        let mut by_lang = HashMap::new();
        by_lang.insert("fr".to_string(), meta(603, "Dune VF"));
        store_localized(&p, crate::metadata_core::ITEM, "m1", &meta(603, "Dune"), &by_lang).unwrap();
        let core = crate::metadata_core::get_core(&p, "item", "m1").unwrap().unwrap();
        assert_eq!(core.tmdb_id, Some(603));
        // Character names are stripped from the invariant core (they live per-lang).
        assert_eq!(core.cast.len(), 1);
        assert!(core.cast[0].character.is_none());
        let fr = crate::translations::resolve_one(&p, "item", "m1", "fr").unwrap().unwrap();
        assert_eq!(fr.title.as_deref(), Some("Dune VF"));
        assert_eq!(fr.characters, vec![Some("Paul".to_string())]);

        let (items_cleared, shows_cleared) = reset_all_metadata(&p).unwrap();
        assert_eq!((items_cleared, shows_cleared), (1, 1));
        assert!(crate::get_item(&p, "m1").unwrap().unwrap().metadata.is_none());
        assert!(crate::metadata_core::get_core(&p, "item", "m1").unwrap().is_none());
        assert!(crate::translations::resolve_one(&p, "item", "m1", "fr").unwrap().is_none());
    }

    #[test]
    fn set_item_and_show_title_rename_the_catalog_row() {
        let p = pool();
        {
            let conn = p.get().unwrap();
            conn.execute(
                "INSERT INTO libraries (id,name,kind,path,added_at) VALUES ('lib','L','movies','/x','t')",
                [],
            )
            .unwrap();
            conn.execute(
                "INSERT INTO items (id,kind,title,container,library,added_at) VALUES ('m1','movie','2001','mkv','lib','t')",
                [],
            )
            .unwrap();
            conn.execute(
                "INSERT INTO shows (id,library,title,added_at) VALUES ('s1','lib','Show','t')",
                [],
            )
            .unwrap();
        }
        set_item_title(&p, "m1", "2001: A Space Odyssey").unwrap();
        set_show_title(&p, "s1", "Severance").unwrap();
        assert_eq!(crate::get_item(&p, "m1").unwrap().unwrap().title, "2001: A Space Odyssey");
        let show_title: String = p
            .get()
            .unwrap()
            .query_row("SELECT title FROM shows WHERE id = 's1'", [], |r| r.get(0))
            .unwrap();
        assert_eq!(show_title, "Severance");
    }

    #[test]
    fn season_cast_and_clear_metadata() {
        let p = pool();
        {
            let conn = p.get().unwrap();
            conn.execute(
                "INSERT INTO libraries (id,name,kind,path,added_at) VALUES ('lib','L','shows','/x','t')",
                [],
            )
            .unwrap();
            conn.execute(
                "INSERT INTO items (id,kind,title,container,library,added_at) VALUES ('m1','movie','Dune','mkv','lib','t')",
                [],
            )
            .unwrap();
            conn.execute(
                "INSERT INTO shows (id,library,title,added_at) VALUES ('s1','lib','Show','t')",
                [],
            )
            .unwrap();
        }
        assert!(seasons_with_cast(&p, "s1").unwrap().is_empty());
        let cast = vec![CastMember { name: "Adam".into(), character: Some("Mark".into()), profile_url: None }];
        set_season_cast(&p, "s1", 1, &cast).unwrap();
        set_season_cast(&p, "s1", 2, &cast).unwrap();
        set_season_cast(&p, "s1", 1, &cast).unwrap(); // idempotent upsert
        let mut seasons: Vec<u32> = seasons_with_cast(&p, "s1").unwrap().into_iter().collect();
        seasons.sort_unstable();
        assert_eq!(seasons, vec![1, 2]);
        let casts = season_casts(&p, "s1").unwrap();
        assert_eq!(casts.len(), 2);
        assert_eq!(casts[&1][0].name, "Adam");

        set_item_metadata(&p, "m1", &meta(603, "Dune")).unwrap();
        set_show_metadata(&p, "s1", &meta(1396, "Show")).unwrap();
        store_localized(&p, metadata_core::ITEM, "m1", &meta(603, "Dune"), &HashMap::new()).unwrap();
        crate::set_item_vector(&p, "m1", &[0.5, 0.5]).unwrap();
        clear_subject_metadata(&p, metadata_core::ITEM, "m1").unwrap();
        clear_subject_metadata(&p, metadata_core::SHOW, "s1").unwrap();
        assert!(crate::get_item(&p, "m1").unwrap().unwrap().metadata.is_none());
        assert!(crate::get_show(&p, "s1").unwrap().unwrap().show.metadata.is_none());
        assert!(metadata_core::get_core(&p, metadata_core::ITEM, "m1").unwrap().is_none());
        assert!(!crate::has_vector(&p, "m1").unwrap());
        assert!(seasons_with_cast(&p, "s1").unwrap().is_empty());
    }

    #[test]
    fn a_language_that_translates_nothing_leaves_no_row_behind() {
        let p = pool();
        let bare = Metadata { title: None, overview: None, genres: Vec::new(), cast: Vec::new(), ..meta(603, "Dune") };
        let by_lang = HashMap::from([("de".to_string(), bare)]);
        store_localized(&p, metadata_core::ITEM, "m1", &meta(603, "Dune"), &by_lang).unwrap();

        assert!(crate::translations::resolve_one(&p, "item", "m1", "de").unwrap().is_none());
    }
}
