#!/usr/bin/env bun
// Generates packages/ui/src/styles/tokens/*.css from the TypeScript tokens, so
// the design system has one source of truth. `bun run tokens:check` regenerates
// and fails on any diff.

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { colors } from '../src/core/tokens/colors';
import { glow, motion, RING_GAP, RING_WIDTH, shadow } from '../src/core/tokens/effects';
import { gutter, radius, rhythm, space } from '../src/core/tokens/layout';
import { fonts, tracking, typeSpec } from '../src/core/tokens/typography';

const OUT = fileURLToPath(new URL('../src/styles/tokens/', import.meta.url));
const HEAD = '/* GENERATED by packages/ui/scripts/gen-token-css.ts. Do not edit by hand. */\n';

const block = (lines: string[]) => `${HEAD}:root {\n${lines.join('\n')}\n}\n`;
const bezier = (b: readonly number[]) => `cubic-bezier(${b.join(', ')})`;
const section = (title: string) => ['', `  /* ${title} */`];

// Explicit rather than derived: `surface1` and `h265` do not kebab-case the same
// way, and these names are a contract the web + desktop stylesheets consume.
const CSS_COLOR: Record<keyof typeof colors, string> = {
  bg: 'bg',
  surface1: 'surface-1',
  surface2: 'surface-2',
  surface3: 'surface-3',
  overlay: 'overlay',
  border: 'border',
  borderStrong: 'border-strong',
  text: 'text',
  textMuted: 'text-muted',
  textDim: 'text-dim',
  accent: 'accent',
  accentHover: 'accent-hover',
  accentBright: 'accent-bright',
  accentInk: 'accent-ink',
  accentWash: 'accent-wash',
  accentSoft: 'accent-soft',
  accentSoftHover: 'accent-soft-hover',
  success: 'success',
  info: 'info',
  hdr: 'hdr',
  h265: 'h265',
  danger: 'danger',
  dangerHover: 'danger-hover',
  wash: 'wash',
};

const color = (k: keyof typeof colors, note = '') => {
  const trailing = note ? ` /* ${note} */` : '';
  return `  --kroma-${CSS_COLOR[k]}: ${colors[k].toLowerCase()};${trailing}`;
};

// `CSS_COLOR` being exhaustive only proves a token has a CSS name; emission below
// is a hand-ordered list, so a token added to colors.ts and forgotten here would
// silently never exist as a custom property.
function assertEveryColourEmitted(css: string): void {
  const missing = (Object.keys(colors) as (keyof typeof colors)[]).filter(
    (k) => !css.includes(`--kroma-${CSS_COLOR[k]}:`),
  );
  if (missing.length > 0) {
    throw new Error(
      `colors.ts declares ${missing.join(', ')} but colorsCss() never emits it. ` +
        'Add it to the section it belongs to in gen-token-css.ts.',
    );
  }
}

function colorsCss(): string {
  return block([
    '  /* Surfaces: deep cinematic charcoal */',
    ...(
      [
        'bg',
        'surface1',
        'surface2',
        'surface3',
        'overlay',
        'border',
        'borderStrong',
        'wash',
      ] as const
    ).map((k) => color(k)),
    ...section('Text on dark'),
    ...(['text', 'textMuted', 'textDim'] as const).map((k) => color(k)),
    ...section('Brand accent: warm amber'),
    ...(
      [
        'accent',
        'accentHover',
        'accentBright',
        'accentInk',
        'accentWash',
        'accentSoft',
        'accentSoftHover',
      ] as const
    ).map((k) => color(k)),
    ...section('Semantic + quality badges'),
    color('success', 'Disponible / Vu'),
    color('info', 'Recherche / reseau'),
    color('hdr', 'badge HDR'),
    color('h265', 'badge H.265'),
    color('danger'),
    color('dangerHover', 'pointer resting on a destructive action'),
    ...section('Semantic aliases'),
    '  --surface-page: var(--kroma-bg);',
    '  --surface-card: var(--kroma-surface-1);',
    '  --surface-raised: var(--kroma-surface-2);',
    '  --text-body: var(--kroma-text);',
    '  --text-secondary: var(--kroma-text-muted);',
    '  --text-tertiary: var(--kroma-text-dim);',
    '  --brand: var(--kroma-accent);',
    '  --brand-ink: var(--kroma-accent-ink);',
  ]);
}

function spacingCss(): string {
  return block([
    ...Object.entries(space).map(([k, v]) => `  --space-${k}: ${v}px;`),
    ...section('Layout gutters'),
    `  --gutter-web: ${gutter.web}px; /* desktop page side padding */`,
    `  --gutter-tv: ${gutter.tv}px; /* 10-foot side padding */`,
    `  --gutter-mobile: ${gutter.mobile}px;`,
    ...section('Component rhythm'),
    `  --row-gap: ${rhythm.rowGap}px; /* carousel card gap (web) */`,
    `  --card-w: ${rhythm.cardWidth}px; /* default poster width (web) */`,
  ]);
}

const RADIUS_NOTE: Partial<Record<keyof typeof radius, string>> = {
  md: 'buttons',
  lg: 'posters / cards',
  xl: 'large cards, rails',
  '2xl': 'panels, modals',
};

function effectsCss(): string {
  // Rings reference var(--kroma-accent) rather than the literal hex, so a themed
  // override of the accent still retints them.
  return block([
    '  /* Corner radii */',
    ...Object.entries(radius).map(([k, v]) => {
      const note = RADIUS_NOTE[k as keyof typeof radius];
      const trailing = note ? ` /* ${note} */` : '';
      return `  --radius-${k}: ${v}px;${trailing}`;
    }),
    ...section('Elevation'),
    ...Object.entries(shadow).map(([k, v]) => `  --shadow-${k}: ${v};`),
    ...section('Focus + glow (10-foot / TV)'),
    `  --ring-width: ${RING_WIDTH}px; /* one width for every focus visual */`,
    `  --ring-gap: ${RING_GAP}px; /* how far it stands off the control */`,
    // An `outline` value, not a `box-shadow` one: the gap is only a gap when
    // nothing fills it (see tokens/effects). Used as
    // `outline: var(--ring-outline); outline-offset: var(--ring-gap);`.
    `  --ring-outline: ${RING_WIDTH}px solid var(--kroma-accent);`,
    ...Object.entries(glow).map(([k, v]) => `  --glow-${k}: ${v};`),
    ...section('Motion'),
    `  --ease-out: ${bezier(motion.bezier.out)};`,
    `  --ease-spring: ${bezier(motion.bezier.spring)};`,
    ...Object.entries(motion.duration).map(([k, v]) => `  --dur-${k}: ${v / 1000}s;`),
    `  --press-scale: ${motion.pressScale}; /* buttons shrink on :active */`,
    `  --hover-lift: ${motion.focusLift}px; /* cards translateY on hover */`,
  ]);
}

const kebab = (key: string) => key.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);

function typographyCss(): string {
  const role = (s: (typeof typeSpec)[keyof typeof typeSpec]) =>
    `${s.weight} ${s.size}px / ${s.ratio} var(--font-${s.family})`;
  return block([
    '  /* Families: display grotesk for titles, humanist grotesk for UI */',
    `  --font-display: "${fonts.display}", system-ui, sans-serif;`,
    `  --font-ui: "${fonts.ui}", system-ui, sans-serif;`,
    ...section('Roles (font shorthand: weight size/line family)'),
    ...Object.entries(typeSpec).map(([k, v]) => `  --type-${kebab(k)}: ${role(v)};`),
    ...section('Tracking, in em. The overline roles are also text-transform:uppercase'),
    ...Object.entries(tracking).map(([k, v]) => `  --tracking-${kebab(k)}: ${v}em;`),
  ]);
}

const colorsOut = colorsCss();
assertEveryColourEmitted(colorsOut);

const files: Record<string, string> = {
  'colors.css': colorsOut,
  'spacing.css': spacingCss(),
  'effects.css': effectsCss(),
  'typography.css': typographyCss(),
};

for (const [name, body] of Object.entries(files)) {
  writeFileSync(OUT + name, body);
  console.log(`wrote ${name} (${body.split('\n').length - 1} lines)`);
}
