import tailwindcss from '@tailwindcss/vite';
import { tanstackStart } from '@tanstack/react-start/plugin/vite';
import react from '@vitejs/plugin-react';
import { fileURLToPath } from 'node:url';
import { defineConfig } from 'vite';

const repoRoot = fileURLToPath(new URL('../..', import.meta.url));

export default defineConfig({
  // Tailwind v4 + TanStack Start (SSR) + React. Route tree generated by Start.
  plugins: [tailwindcss(), tanstackStart(), react()],
  // `#web/*` → this app's src (mirrors tsconfig.base paths; Vite needs it explicitly).
  resolve: { alias: { '#web': fileURLToPath(new URL('./src', import.meta.url)) } },
  server: {
    // Allow importing TS source from the workspace packages (@luma/ui, @luma/core).
    fs: { allow: [repoRoot] },
  },
  // Workspace packages ship raw TS source — bundle them for SSR (don't externalize).
  ssr: { noExternal: ['@luma/ui', '@luma/core'] },
  optimizeDeps: { exclude: ['@luma/ui', '@luma/core'] },
});
