import { execFile } from 'node:child_process';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { promisify } from 'node:util';
import type { Plugin } from 'vite';
import { OG_CARDS } from './og-cards';

const run = promisify(execFile);
const here = dirname(fileURLToPath(import.meta.url));

// The Open Graph social cards, one PNG per locale, GENERATED BY THE BUILD.
//
// They used to be two 190 KB PNGs written by a `bun run og` script and committed
// under `public/`, which made a build ARTEFACT a tracked source file: the card went
// stale silently whenever the tokens, the fonts or the wording moved, and the only
// thing keeping it honest was remembering to run a script by hand. Generated here it
// is derived from the same sources as the pages that link to it, every time, and
// there is no committed binary to drift.
//
// The drawing happens in ./og-render.tsx, under bun - see that file for why it cannot
// be called in-process from here.

/** Bun runs the renderer. Prefer the interpreter already running this build over a
 *  PATH lookup: `bun run build` means `process.execPath` IS bun. */
const bun = /bun(\.exe)?$/.test(process.execPath) ? process.execPath : 'bun';

async function renderAll(): Promise<Map<string, Buffer>> {
  // Base64 over stdout, keyed by filename. Two 2400x1260 PNGs is a few hundred KB through
  // a pipe, and the alternative - a temp directory for the child to write into - meant a
  // filesystem path to hand over, validate and clean up for bytes that only ever needed to
  // reach memory. `maxBuffer` because execFile's 1 MB default would truncate them.
  const { stdout } = await run(bun, [join(here, 'og-render.tsx')], {
    maxBuffer: 32 * 1024 * 1024,
  });
  const cards: Record<string, string> = JSON.parse(stdout);
  return new Map(
    Object.entries(cards).map(([file, base64]) => [file, Buffer.from(base64, 'base64')]),
  );
}

export function ogPlugin(): Plugin {
  // One render per process, shared by the dev middleware and the build: rasterizing
  // two cards at 2x is the expensive half, and nothing they are drawn from can change
  // without restarting the process that loaded this module.
  let cards: Promise<Map<string, Buffer>> | undefined;
  const all = () => {
    cards ??= renderAll();
    return cards;
  };

  return {
    name: 'kroma:og',

    // Dev serves the cards from memory at the same paths the built site uses, so a
    // card debugger pointed at `bun run dev` sees the real image rather than a 404
    // that only exists outside production.
    configureServer(server) {
      const wanted = new Set<string>(Object.values(OG_CARDS).map((c) => c.file));
      server.middlewares.use((req, res, next) => {
        const file = req.url?.split('?')[0]?.replace(/^\//, '') ?? '';
        if (!wanted.has(file)) return next();
        all()
          .then((byFile) => {
            const png = byFile.get(file);
            if (!png) return next();
            res.setHeader('content-type', 'image/png');
            res.setHeader('cache-control', 'no-cache');
            res.end(png);
          })
          .catch(next);
      });
    },

    // The client build is the one whose output Cloudflare serves (dist/client) and the
    // only environment that should carry the asset; the server/prerender build would
    // write a second, unreachable copy.
    async generateBundle() {
      if (this.environment?.name !== 'client') return;
      for (const [fileName, source] of await all()) {
        this.emitFile({ type: 'asset', fileName, source });
      }
    },
  };
}
