import { defaultLocale, type Lang, locales, localizePath } from '#site/lib/i18n';
import { site } from '#site/lib/site';
import { m } from '#site/paraglide/messages';

export interface SeoInput {
  /** The locale this head is for. Drives the canonical URL, the hreflang
   *  alternates and the og:locale. */
  lang: Lang;
  title?: string;
  description?: string;
  /** The CANONICAL (French) path, e.g. `/download`. The locale prefix is added
   *  here, and every locale's URL is emitted as an hreflang alternate. */
  path?: string;
  /** Root-relative image path for the social card. Defaults to the locale's own
   *  card — pass this only for a page with bespoke art (a blog post's cover). */
  image?: string;
  /** `article` on blog posts, `website` everywhere else. */
  type?: 'website' | 'article';
}

const ogLocale: Record<Lang, string> = { fr: 'fr_FR', en: 'en_US' };

/**
 * The social card, per locale.
 *
 * A card is an IMAGE, so unlike the page around it there is no request-time
 * translation: whatever the scraper fetched is what every reader of that shared
 * link sees. Without this, a French page previewed in English — the one place a
 * bilingual site visibly leaks its default language. Generated by `bun run og`
 * (scripts/og.tsx); the base locale keeps the unsuffixed name so an old shared
 * link still resolves.
 */
const ogCard: Record<Lang, string> = { en: '/og.png', fr: '/og.fr.png' };

/**
 * Build the `meta`/`links` a route hands to TanStack Start's <HeadContent>.
 * A page passes its locale and the bits it changes; the brand suffix, the Open
 * Graph, the Twitter card, the canonical URL and the per-locale hreflang
 * alternates are filled in here so every page ships a complete, consistent, and
 * correctly cross-linked social + SEO head without repeating the boilerplate.
 */
export function seo({ lang, title, description, path = '/', image, type = 'website' }: SeoInput) {
  // Straight from the catalog for the locale being rendered. It used to be
  // `lang === 'fr' ? site.tagline : site.taglineEn`, which is the shape this package
  // spent a refactor removing: a third language would silently have been served
  // English here, in the two strings a search result actually shows.
  const fullTitle = title ? `${title} · ${site.name}` : `${site.name} · ${m.site_tagline()}`;
  const desc = description ?? m.site_description();
  const url = `${site.url}${localizePath(path, lang)}`;
  const card = image ?? ogCard[lang];
  const cardUrl = card.startsWith('http') ? card : `${site.url}${card}`;

  return {
    meta: [
      { title: fullTitle },
      { name: 'description', content: desc },
      { property: 'og:type', content: type },
      { property: 'og:site_name', content: site.name },
      { property: 'og:locale', content: ogLocale[lang] },
      { property: 'og:title', content: fullTitle },
      { property: 'og:description', content: desc },
      { property: 'og:url', content: url },
      { property: 'og:image', content: cardUrl },
      // The card is an image of text, so a reader on a screen reader gets nothing
      // from it without this. The page's own description IS the card's meaning.
      { property: 'og:image:alt', content: desc },
      { name: 'twitter:card', content: 'summary_large_image' },
      { name: 'twitter:title', content: fullTitle },
      { name: 'twitter:description', content: desc },
      { name: 'twitter:image', content: cardUrl },
    ],
    links: [
      { rel: 'canonical', href: url },
      // Every locale points at every locale (Google needs the reciprocal set),
      // plus x-default on the BASE locale's URL — the one served to a reader whose
      // language we do not publish. It followed the French root while French was
      // the default; English is, so pointing it at /fr would have advertised the
      // French page as the fallback for the entire rest of the world.
      ...locales.map((l) => ({
        rel: 'alternate',
        hreflang: l,
        href: `${site.url}${localizePath(path, l)}`,
      })),
      {
        rel: 'alternate',
        hreflang: 'x-default',
        href: `${site.url}${localizePath(path, defaultLocale)}`,
      },
    ],
  };
}
