import { defaultLocale, type Lang, locales, localizePath } from '#site/lib/i18n';
import { site } from '#site/lib/site';
import { m } from '#site/paraglide/messages';

export interface SeoInput {
  lang: Lang;
  title?: string;
  description?: string;
  path?: string;
  image?: string;
  type?: 'website' | 'article';
}

const ogLocale: Record<Lang, string> = { fr: 'fr_FR', en: 'en_US' };

// A card is an image, so unlike the page around it there is no request-time
// translation: whatever the scraper fetched is what every reader of that
// shared link sees. Generated by `bun run og` (scripts/og.tsx); the base
// locale keeps the unsuffixed name so an old shared link still resolves.
const ogCard: Record<Lang, string> = { en: '/og.png', fr: '/og.fr.png' };

/** Build the `meta`/`links` a route hands to TanStack Start's <HeadContent>.
 *  A page passes its locale and the bits it changes; the brand suffix, Open
 *  Graph, Twitter card, canonical URL and hreflang alternates are filled in
 *  here. */
export function seo({ lang, title, description, path = '/', image, type = 'website' }: SeoInput) {
  // Straight from the catalog for the locale being rendered: a per-language
  // ternary here would silently serve English to a third language, in the
  // two strings a search result actually shows.
  const fullTitle = title ? `${title} · ${site.name}` : `${site.name} · ${m.site_tagline()}`;
  const desc = description ?? m.site_description();
  const url = `${site.url}${localizePath(path, lang)}`;
  const card = image ?? ogCard[lang];
  const cardUrl = card.startsWith('http') ? card : `${site.url}${card}`;

  return {
    meta: [
      { title: fullTitle },
      { name: 'description', content: desc },
      { property: 'og:type', content: type },
      { property: 'og:site_name', content: site.name },
      { property: 'og:locale', content: ogLocale[lang] },
      { property: 'og:title', content: fullTitle },
      { property: 'og:description', content: desc },
      { property: 'og:url', content: url },
      { property: 'og:image', content: cardUrl },
      // The card is an image of text, so a screen reader gets nothing from it
      // without this; the page's own description is the card's meaning.
      { property: 'og:image:alt', content: desc },
      { name: 'twitter:card', content: 'summary_large_image' },
      { name: 'twitter:title', content: fullTitle },
      { name: 'twitter:description', content: desc },
      { name: 'twitter:image', content: cardUrl },
    ],
    links: [
      { rel: 'canonical', href: url },
      // Every locale points at every locale (Google needs the reciprocal set),
      // plus x-default on the BASE locale's URL, served to a reader whose
      // language we do not publish.
      ...locales.map((l) => ({
        rel: 'alternate',
        hreflang: l,
        href: `${site.url}${localizePath(path, l)}`,
      })),
      {
        rel: 'alternate',
        hreflang: 'x-default',
        href: `${site.url}${localizePath(path, defaultLocale)}`,
      },
    ],
  };
}
