// Sets FLAG_KEEP_SCREEN_ON in onCreate, so an Android TV stays awake for the
// activity's whole life rather than only while the React root is mounted (which
// is all `useKeepAwake` can promise). A config plugin because
// clients/tv-native/android is generated by `expo prebuild`.

import type { ConfigPlugin } from 'expo/config-plugins';
import { createRunOncePlugin, withMainActivity } from 'expo/config-plugins';

const IMPORT_ANCHOR = 'import android.os.Bundle';
const IMPORT = 'import android.view.WindowManager';

// Matches whatever the template passes down - `null` today, because
// expo-splash-screen rewrites the call, and `savedInstanceState` before that.
const ONCREATE = /super\.onCreate\([^)]*\)/;
const KEEP_SCREEN_ON = `
    // Android TV: see plugins/with-keep-screen-on.ts.
    window.addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON)`;

const withKeepScreenOn: ConfigPlugin = (config) =>
  withMainActivity(config, (cfg) => {
    let contents = cfg.modResults.contents;
    // Idempotent: prebuild without --clean re-runs plugins over a patched file.
    if (contents.includes('FLAG_KEEP_SCREEN_ON')) return cfg;

    if (!contents.includes(IMPORT_ANCHOR)) {
      throw new Error(
        'with-keep-screen-on: could not find the Bundle import in MainActivity.kt. ' +
          'The Expo template changed - re-point this plugin, or the television will ' +
          'go to sleep mid-film.',
      );
    }
    contents = contents.replace(IMPORT_ANCHOR, `${IMPORT_ANCHOR}\n${IMPORT}`);

    if (!ONCREATE.test(contents)) {
      throw new Error(
        'with-keep-screen-on: could not find super.onCreate() in MainActivity.kt. ' +
          'The Expo template changed - re-point this plugin, or the television will ' +
          'go to sleep mid-film.',
      );
    }
    cfg.modResults.contents = contents.replace(ONCREATE, (call) => `${call}${KEEP_SCREEN_ON}`);
    return cfg;
  });

export default createRunOncePlugin(withKeepScreenOn, 'kroma-keep-screen-on', '1.0.0');
