// Installs Conscrypt as the top JSSE provider on Android 9 and older, which is
// where the platform stack stops at TLS 1.2 (Android 10 was the release that
// enabled TLS 1.3 by default). A box like the Mi Box 4 otherwise cannot
// handshake with a server whose edge sets a TLS 1.3 floor, and the failure
// reaches the screen as "no server answers this address".
//
// OkHttp, which every fetch in the app goes through, switches to its Conscrypt
// platform on its own once the provider sits first. A config plugin because
// clients/tv-native/android is generated by `expo prebuild`.

import type { ConfigPlugin } from 'expo/config-plugins';
import { createRunOncePlugin, withAppBuildGradle, withMainApplication } from 'expo/config-plugins';

const CONSCRYPT = 'org.conscrypt:conscrypt-android:2.5.3';

const GRADLE_ANCHOR = 'implementation("com.facebook.react:react-android")';
const GRADLE_DEPENDENCY = `    implementation("${CONSCRYPT}")`;

const IMPORT_ANCHOR = 'import android.app.Application';
const IMPORTS = [
  'import android.os.Build',
  'import java.security.Security',
  'import org.conscrypt.Conscrypt',
].join('\n');

const ONCREATE_ANCHOR = 'super.onCreate()';
const INSTALL = `
    // See plugins/with-conscrypt.ts.
    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.Q) {
      Security.insertProviderAt(Conscrypt.newProvider(), 1)
    }`;

const moved = (what: string) =>
  new Error(
    `with-conscrypt: could not find ${what}. The Expo template changed - re-point ` +
      'this plugin, or an Android 9 television can no longer reach a TLS 1.3 server.',
  );

const withConscryptDependency: ConfigPlugin = (config) =>
  withAppBuildGradle(config, (cfg) => {
    const contents = cfg.modResults.contents;
    if (contents.includes(CONSCRYPT)) return cfg;
    if (!contents.includes(GRADLE_ANCHOR))
      throw moved('the react-android dependency in app/build.gradle');

    cfg.modResults.contents = contents.replace(
      GRADLE_ANCHOR,
      `${GRADLE_ANCHOR}\n${GRADLE_DEPENDENCY}`,
    );
    return cfg;
  });

const withConscryptProvider: ConfigPlugin = (config) =>
  withMainApplication(config, (cfg) => {
    let contents = cfg.modResults.contents;
    if (contents.includes('Conscrypt')) return cfg;

    if (!contents.includes(IMPORT_ANCHOR))
      throw moved('the Application import in MainApplication.kt');
    contents = contents.replace(IMPORT_ANCHOR, `${IMPORT_ANCHOR}\n${IMPORTS}`);

    if (!contents.includes(ONCREATE_ANCHOR)) throw moved('super.onCreate() in MainApplication.kt');
    cfg.modResults.contents = contents.replace(ONCREATE_ANCHOR, `${ONCREATE_ANCHOR}${INSTALL}`);
    return cfg;
  });

const withConscrypt: ConfigPlugin = (config) =>
  withConscryptProvider(withConscryptDependency(config));

export default createRunOncePlugin(withConscrypt, 'kroma-conscrypt', '1.0.0');
