#!/usr/bin/env bun
/**
 * Build a machine-readable index of every requirement in the KROMA spec.
 *
 * An agent (or a person) resolves any requirement ID to its exact location in
 * one lookup instead of grepping prose: read `docs/spec/requirements.json`,
 * find the ID, jump to `file` + `line`. The human-facing `docs/spec/INDEX.md`
 * is generated from the same data so the two never drift.
 *
 * This script is also the enforcement point. It fails (non-zero exit) on:
 *   - a duplicate requirement ID,
 *   - an unknown domain prefix,
 *   - a requirement line missing a status,
 * so `bun run spec:check` can gate a PR the same way `modules:check` does.
 *
 * It writes nothing when only validating: pass `--check` to validate + regenerate
 * and let the caller `git diff --exit-code` the outputs.
 */

import { readdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

const SPEC_DIR = join(import.meta.dir, "..");

// The fixed domain prefixes. One per spec file; adding a domain means adding here.
const DOMAINS: Record<string, string> = {
  LIB: "library.md",
  MEDIA: "media.md",
  PLAY: "playback.md",
  ACCT: "accounts.md",
  DISC: "discovery.md",
  MOD: "modules.md",
  ADMIN: "admin.md",
  SURF: "surfaces.md",
};

const STATUSES = ["SHIPPED", "AGREED", "DRAFT", "DESIGN, NOT IMPLEMENTED"] as const;
type Status = (typeof STATUSES)[number];

interface Requirement {
  id: string;
  domain: string;
  number: number;
  status: Status;
  text: string;
  file: string;
  line: number;
}

// **LIB-4** (AGREED) — A rescan never deletes user data.
const REQ = /^\s*(?:[-*]\s+)?\*\*([A-Z]+)-(\d+)\*\*\s*\(([^)]+)\)\s*[—-]\s*(.+?)\s*$/;

async function collect(): Promise<{ reqs: Requirement[]; errors: string[] }> {
  const reqs: Requirement[] = [];
  const errors: string[] = [];
  const seen = new Map<string, string>(); // id -> "file:line" of first sighting

  const files = (await readdir(SPEC_DIR)).filter(
    (f) => f.endsWith(".md") && f !== "README.md" && f !== "INDEX.md",
  );

  for (const file of files.sort()) {
    const lines = (await readFile(join(SPEC_DIR, file), "utf8")).split("\n");
    lines.forEach((raw, i) => {
      const m = raw.match(REQ);
      if (!m) return;
      const [, domain, num, statusRaw, text] = m;
      const line = i + 1;
      const where = `${file}:${line}`;

      if (!(domain in DOMAINS)) {
        errors.push(`${where}: unknown domain prefix "${domain}-"`);
        return;
      }
      if (DOMAINS[domain] !== file) {
        errors.push(`${where}: prefix "${domain}-" belongs in ${DOMAINS[domain]}, not ${file}`);
      }
      const status = statusRaw.trim();
      if (!STATUSES.includes(status as Status)) {
        errors.push(`${where}: "${domain}-${num}" has invalid status "${status}"`);
        return;
      }
      const id = `${domain}-${num}`;
      if (seen.has(id)) {
        errors.push(`${where}: duplicate requirement ${id} (first at ${seen.get(id)})`);
        return;
      }
      seen.set(id, where);
      reqs.push({
        id,
        domain,
        number: Number(num),
        status: status as Status,
        text: text.replace(/\s+/g, " "),
        file: `docs/spec/${file}`,
        line,
      });
    });
  }

  reqs.sort((a, b) => a.file.localeCompare(b.file) || a.number - b.number);
  return { reqs, errors };
}

function renderIndex(reqs: Requirement[]): string {
  const out: string[] = [
    "<!-- Generated by docs/spec/scripts/spec-index.ts — do not edit by hand. -->",
    "<!-- Run `bun run spec:index` after changing any requirement. -->",
    "",
    "# Requirement index",
    "",
    `${reqs.length} requirement${reqs.length === 1 ? "" : "s"} across the spec. ` +
      "The machine-readable source is [`requirements.json`](requirements.json).",
    "",
  ];
  const byDomain = new Map<string, Requirement[]>();
  for (const r of reqs) (byDomain.get(r.domain) ?? byDomain.set(r.domain, []).get(r.domain)!).push(r);

  for (const [domain, list] of byDomain) {
    const file = DOMAINS[domain];
    out.push(`## ${domain} — [${file}](${file})`, "");
    for (const r of list) {
      out.push(`- **${r.id}** (${r.status}) — ${r.text}`);
    }
    out.push("");
  }
  return out.join("\n");
}

const check = process.argv.includes("--check");
const { reqs, errors } = await collect();

if (errors.length) {
  console.error("Spec index found problems:\n" + errors.map((e) => `  ✗ ${e}`).join("\n"));
  process.exit(1);
}

await writeFile(join(SPEC_DIR, "requirements.json"), JSON.stringify(reqs, null, 2) + "\n");
await writeFile(join(SPEC_DIR, "INDEX.md"), renderIndex(reqs));

console.log(
  `Spec index: ${reqs.length} requirement(s) written to requirements.json + INDEX.md.` +
    (check ? " Run `git diff --exit-code` to confirm they were committed." : ""),
);
